# -*- coding: utf-8 -*-
"""CLI が画面に出す文字列の日本語。

鍵は `i18n.t()` に渡す**英語の原文そのまま**。原文を直したら、ここの鍵も
直すこと（直し忘れは英語のまま出るだけで落ちない）。
`Messages::test_every_message_has_a_japanese_translation` が、コードの中の
`t('…')` とこの表の過不足を突き合わせる。

埋め込みは `{name}` の名前つき。順番は変えてよいが、**名前は原文と同じもの**
を使うこと（`i18n.t` は渡された名前しか差し替えない）。
"""
from __future__ import annotations

MESSAGES: dict = {
    # -- レポート行の頭の印（i18n.tag）--------------------------------
    '[CJK]': '[日本語]',
    '[Word]': '[Word]',
    '[abstract]': '[要旨]',
    '[accepted]': '[承知のうえ]',
    '[analysis]': '[分析]',
    '[anonymous]': '[匿名]',
    '[assets]': '[資産]',
    '[bib flaws]': '[書誌の傷]',
    '[bib]': '[書誌]',
    '[careful]': '[要注意]',
    '[clash]': '[衝突]',
    '[conditional]': '[条件付き]',
    '[crossref]': '[相互参照]',
    '[fatal]': '[致命的]',
    '[figure]': '[図]',
    '[layout]': '[体裁]',
    '[length]': '[分量]',
    '[missing]': '[欠落]',
    '[note]': '[注意]',
    '[placeholder]': '[仮の値]',
    '[replication]': '[複製]',
    '[script]': '[台本]',
    '[slides]': '[スライド]',
    '[split]': '[分割]',
    '[stopped]': '[中止]',
    '[table]': '[表]',
    '[theorem divs]': '[事例等]',
    '[typeset]': '[組版]',
    '[unused]': '[未使用]',
    '[values]': '[値]',
    '[warning]': '[警告]',
    '[wrote]': '[書いた]',

    # -- 画面に出す文言 ------------------------------------------------
    # 固有名詞とコマンドは訳しようがないので原文のまま載せている
    '  ok  ': '  ok  ',
    '  └ CSL citations': '  └ CSL 引用',
    '  └ R (Rscript)': '  └ R (Rscript)',
    '  └ Typst output': '  └ Typst 書き出し',
    '  └ visible to Typst': '  └ Typst から見えるか',
    ' / {n} duplicate {n|pair|pairs}': '／重複 {n} 組',
    ' note ': ' 注意 ',
    '(already there)': '（既にある）',
    '(lines {a}-{b})': '（{a}-{b} 行）',
    '(make sure this data may be redistributed)': '（再配布してよいデータか、必ず確かめること）',
    '(no bibliography list)': '（一覧は出さない）',
    '(no manuscript)': '（原稿が無い）',
    '(put the raw data in data/raw/ and say where it came from in data/raw/README.md)': '（data/raw/ に原データを置き、data/raw/README.md に出所を書く）',
    '(rewrite analysis/analysis.qmd as your own analysis)': '（analysis/analysis.qmd を自分の分析に書き換える）',
    '(unknown)': '(不明)',
    '({n} watched {n|input|inputs})': '（見張っている入力 {n} 件）',
    '--no-citations: leaving citations unresolved (for a draft)': '--no-citations: 引用を解決しない（下書き用）',
    'All clear. Ready to submit': '問題なし。投稿できる',
    'Analysis': '分析',
    'Analysis (only when you use a .qmd)': '分析（.qmd を使うときだけ）',
    'Beamer theme metropolis': 'Beamer テーマ metropolis',
    'Building now puts fake numbers in the text -> octavo analysis run': 'いま組むと本文には嘘の数字が入る -> octavo analysis run',
    'CJK fonts': '日本語フォント',
    'CSL cache': 'CSL キャッシュ',
    'CSL citations (--citeproc built in)': 'CSL 引用（--citeproc 内蔵）',
    'Ctrl-C to stop': 'Ctrl-C で止める',
    'Every everyday format (typst / docx) works.': 'ふだんの形式（typst / docx）はすべて出せる。',
    'Fix it, then octavo build. To build with results/ as it is: octavo build --no-analysis': '直してから octavo build する。今の results/ のまま変換したいなら octavo build --no-analysis',
    'For LaTeX / Beamer too: {cmd} --with-tex': 'LaTeX / Beamer も使うなら: {cmd} --with-tex',
    "For a newer one, take the .deb from https://github.com/jgm/pandoc/releases (apt's is often old)": '新しい版が要るなら https://github.com/jgm/pandoc/releases から .deb を入れる（apt の版は古いことが多い）',
    'Formats you can produce': '出せる形式',
    'Harano Aji fonts (for LaTeX)': '原ノ味フォント（LaTeX 用）',
    'If it is a result:  add ov_value("name", value) to the .qmd and write {{name}} in the text': '分析結果なら:  .qmd に ov_value("名前", 値) を足し、本文を {{名前}} にする',
    'If it is not:       add the string to lint_accepted in octavo.config.py': '結果でないなら: octavo.config.py の lint_accepted にその文字列を足す',
    'If you did not, something went wrong — the raw data has been overwritten': '差し替えた覚えが無いなら、それは事故（原データが書き換わっている）',
    'If you replaced the data on purpose: octavo analysis run --force, then octavo data hash to record it again': 'データを差し替えたなら octavo analysis run --force のうえ octavo data hash で記録し直す',
    'Japanese document class ltjsarticle': '日本語文書クラス ltjsarticle',
    'Keep this file in git — data/ itself is not, so this is the only record there will be': 'このファイルは git に入れること（data/ 自体は入らないので、これが唯一の記録になる）',
    'LuaLaTeX': 'LuaLaTeX',
    'MISSING': '欠落',
    'Next:': '次にやること:',
    'No drift. This is the same data as when it was recorded': '食い違いなし。記録したときと同じデータで走っている',
    'Nothing recorded yet. Make it with: octavo data hash': 'まだ記録が無い。octavo data hash で作る',
    'OK': 'OK',
    'Python': 'Python',
    'Quarto': 'Quarto',
    'Recorded fingerprints for {n} {n|file|files} in {path}': '{n} ファイルの指紋を {path} に記録した',
    'Recorded {when}: {n} {n|file|files}': '{when} の記録: {n} ファイル',
    'References cited:': '引用している文献:',
    'Starting from nothing: octavo init my-paper': '一から作るなら: octavo init my-paper',
    'TeX (only when you use LaTeX / Beamer)': 'TeX（LaTeX / Beamer を使うときだけ）',
    'The working rules are in CLAUDE.md, the walkthrough in README.md.': '作業の約束事は CLAUDE.md、手順は README.md に書いてある。',
    'To install them all: {cmd}': 'まとめて入れるなら: {cmd}',
    'Tools': '道具',
    'Typst': 'Typst',
    'Typst 0.12 or newer': 'Typst 0.12 以上',
    'Typst can see no CJK font': 'Typst から見える日本語フォントが無い',
    'Typst output (-t typst)': 'Typst 書き出し（-t typst）',
    'What to add': '足すもの',
    'Wrote a project skeleton in {path}:': '{path} にひな型を作った:',
    'Wrote {path}. Open it in Word, set up the styles (Heading 1, Body Text, Table Caption and so on), then write this in octavo.config.py:': '{path} を作った。Word で開いてスタイル（見出し 1、本文、Table Caption 等）を整え、octavo.config.py に次を書く:',
    'Zotero collection name (leave it out for the whole library)': 'Zotero のコレクション名（省略で全体）',
    'Zotero is not answering': 'Zotero が応答しない',
    'Zotero is not answering ({where}).': 'Zotero が応答しない（{where}）。',
    'Zotero local API / collection {name}': 'Zotero ローカル API / コレクション {name}',
    'Zotero local API / the whole library': 'Zotero ローカル API / ライブラリ全体',
    '\\poscite{{{key}}}: no such key in the .bib': '\\poscite{{{key}}}: .bib にキーが無い',
    'a CJK font for Typst': 'Typst 用の日本語フォント',
    "a Typst numbering string ('1.' and the like) or None": "Typst の numbering 文字列（'1.' など）か None",
    'a Word file for your coauthors': '共著者に回す Word',
    'a conditional': '条件分岐',
    'a document called {name} already exists ({path})': '同じ名前の文書が既にある: {name}（{path}）',
    "a hex colour like '#0e2f92', or None": "'#0e2f92' のような16進の色か None",
    'a style ID or an alias': 'スタイル ID か別名',
    'add TeX and this works (missing: {what})': 'TeX を足せば出せる（足りない: {what}）',
    'add a manuscript': '原稿を足す',
    'add a manuscript (as many as you like)': '原稿を足す（何本でも）',
    'add a manuscript (paper, slides or lecture notes)': '原稿を足す（論文・スライド・講義ノート）',
    'add one with octavo new paper|slides|lecture <name>, or check documents in octavo.config.py': 'octavo new paper|slides|lecture <名前> で足すか、octavo.config.py の documents を確かめる',
    'add the blind-review checks as well (self-citations and the like)': '匿名審査で出すときの検査も足す（自己引用など）',
    'added': '増えた値',
    'aliases:': '別名:',
    '{n|the one is|all # are} in the .bib': '{n} 件すべて .bib にある',
    '{n|the one is|all # are} up to date': '{n} 本とも最新',
    '{n|the one is|all # are} up to date (not running {n|it|them})': '{n} 本とも最新（走らせない）',
    '{n|the one resolves|all # resolve}': '{n} 個すべて解決できる',
    'also list entries you never cite': '引いていない書誌も出す',
    'also list values the text does not use': '本文が使っていない値も出す',
    'analysis': '分析',
    'analysis freshness': '分析の鮮度',
    "analysis takes either 'analysis.qmd' or {{'src': '…', 'deps': ['data/*.csv'], 'manual': True}} (got {got})": "analysis には 'analysis.qmd' か {{'src': '…', 'deps': ['data/*.csv'], 'manual': True}} の形で書く（いまは {got}）",
    'appendix': '付録',
    'are you reaching for a Windows Zotero from inside WSL? (then either put WSL2 in mirrored networking mode, or export the library from Zotero by hand and put it at bib_file)': 'WSL から Windows の Zotero を見ようとしていないか（その場合は WSL2 のネットワークモードを mirrored にするか、Zotero 側で手動でライブラリを書き出して bib_file に置くこと）',
    'beamer': 'beamer',
    'bib': '書誌',
    'bib contents': '書誌の中身',
    'biber': 'biber',
    'biber (not needed with CSL)': 'biber（CSL 運用では不要）',
    'bold paragraphs, unnumbered': '通し番号無しのボールド段落',
    'build a small manuscript for real and show how the citations come out': '小さな原稿を実際に通して、引用の組み方を見せる',
    'build document example-paper as Word': '文書 example-paper を Word にする',
    'build every format, typeset them too': '出せる形式を全部作って組版まで',
    'build everything the config says': '設定どおりに全部作る',
    'build for blind review (hide anything identifying)': '匿名審査用に組む（著者が分かる箇所を伏せる）',
    'build it (a stale analysis runs first)': '変換する（分析が古ければ先に走る）',
    'build the appendix too': '付録も変換する',
    'build the manuscripts': '原稿を変換する',
    'building only session {part} of {file}': '{file} の {part} 回だけを組む',
    'building with anything identifying hidden (::: {.no-anonymous} blocks and the title-block metadata)': '著者が分かる箇所を伏せて組む（::: {.no-anonymous} で囲んだ部分と題扉のメタデータ）',
    'bundle packs one format at a time (--to typst, say)': 'bundle は1つの形式だけを固める（--to typst など）',
    'cannot compare with git: {why}': 'git と比べられない: {why}',
    'cannot list the collections ({why})': 'コレクション一覧を取れない（{why}）',
    'cannot read {file}: {why}': '{file} を読めない: {why}',
    'cannot read {path} as a .docx ({why})': '.docx として読めない: {path}（{why}）',
    'cannot run git: {why}': 'git を呼べない: {why}',
    'cannot run it: {why}': '走らせられない: {why}',
    'check that the words around them ("slightly", "about" and the like) still hold': '本文の言い回し（「わずかに」「約」など）も合っているか確かめること',
    'citation keys': '引用キー',
    'comment': 'コメント',
    'comments only': 'コメントだけ',
    'compared with {when}': '{when} の時点との比較',
    'contents differ': '中身が違う',
    'converted {n} theorem {n|div|divs} ({how})': 'theorem div を {n} 個変換した（{how}）',
    'could not fetch the CSL style {id}: {why}': 'CSL スタイル {id} を取れなかった: {why}',
    "could not fetch the CSL, but chicago-author-date is pandoc's built-in default — carrying on": 'CSL を取れなかったが chicago-author-date は pandoc の内蔵既定なのでそのまま進む',
    'could not get the default reference.docx out of pandoc:': 'pandoc の既定 reference.docx を取り出せなかった:',
    'cross-check citation keys against the .bib': '引用キーと .bib の突き合わせ',
    'cross-check {{…}} against results/': '本文の {{…}} と results/ の突き合わせ',
    'cross-check {{…}} in the text against results/': '本文の {{…}} と results/ の突き合わせ',
    'cut it down, or check the journal rules': '削るか、雑誌の規定を確かめる',
    'data': 'データ',
    'data fingerprints': 'データの指紋',
    'data/raw is not included (--with-raw-data adds it, once you have checked it may be shared)': 'data/raw は入れていない（--with-raw-data で入る。再配布の可否を確かめてから）',
    'decimal': '小数',
    'decimal in parentheses (a standard error?)': '括弧内の小数（標準誤差？）',
    'deleted': '削除',
    'diagnose the environment': '環境の診断',
    'did you mean: {key}': 'もしかして: {key}',
    'display language': '表示の言語',
    'do not go and fetch a CSL': 'CSL を取りに行かない',
    'do not run the .qmd (build with results/ as it is)': '.qmd を走らせない（いまの results/ のまま変換する）',
    'document names (default: all of them)': '文書の名前（既定: 全部）',
    'documents': '文書',
    'documents in octavo.config.py is not picking up {glob} — check it': 'octavo.config.py の documents が {glob} を拾っていない。documents を確かめること',
    "documents['{name}'] has a bad profile: {got} (one of {allowed})": "documents['{name}'] の profile が不正: {got}（{allowed}）",
    "documents['{name}'] has bad targets: {bad}": "documents['{name}'] の targets が不正: {bad}",
    "documents['{name}'] needs at least 'src'": "documents['{name}'] には少なくとも 'src' が要る",
    'dropped {n} {n|block that does|blocks that do} not belong in this output': '用途に合わないブロック {n} 個を落とした',
    'dropped {n} needless {n|field|fields} and wrote {path} (the original is untouched)': '{n} 個の余計なフィールドを落として {path} に書いた（元のファイルは触っていない）',
    'e.g.': '例:',
    'environment record': '環境の記録',
    'every figure the text uses is there': '本文が貼っている図は揃っている',
    'every one matches a .qmd': '全部が .qmd に対応している',
    'every {{…}} in the text resolves': '本文の {{…}} はすべて解決できる',
    'failed:': '失敗:',
    'failed: {unit}': '失敗: {unit}',
    'fatal ': '致命的',
    "fetch a journal's style (CSL)": '雑誌の書式（CSL）を取ってくる',
    'fetch it with: octavo csl get {id}': 'octavo csl get {id}   で取得できる',
    'fetch the .bib from Zotero': 'Zotero から .bib を取ってくる',
    'fetched the CSL: {path}': 'CSL を取得した: {path}',
    'figure files': '図のファイル',
    'figures/trend.png (and .pdf — placeholders)': 'figures/trend.png（と .pdf。仮の図）',
    'files under data/ right now: {n}': 'いま data/ にあるファイル: {n} 件',
    'find results typed into the manuscript': '原稿に直書きされた数値を探す',
    'fontconfig': 'fontconfig',
    'for blind review (run octavo build --anonymous first)': '匿名審査用（先に octavo build --anonymous）',
    'for blind review, decide whether to mask them as Author (year) — it depends on the journal': '匿名審査なら Author (年) に伏せるか判断する（雑誌の規定による）',
    'format (default: typst)': '形式（既定: typst）',
    'formats (default: everything that works)': '形式（既定: 出せるもの全部）',
    'found nothing that looks like a hand-typed result': '原稿に直書きされた分析結果らしき数値は見つからなかった',
    'fresh': '最新',
    'octavo analysis run, or check the spelling of the name': 'octavo analysis run、または名前の綴りを確かめる',
    'octavo analysis run, or put it in figures/': 'octavo analysis run、または figures/ に置く',
    'octavo build <name> could not tell them apart — pick another': 'octavo build <名前> で区別できなくなるので、別の名前にすること',
    'octavo checkbib (what you decide not to fix goes in bib_accepted)': 'octavo checkbib（直さないと決めたものは bib_accepted へ）',
    'octavo data hash to record / status to check': 'octavo data hash で記録する / status で確かめる',
    'octavo lint (what is not a result goes in lint_accepted)': 'octavo lint（結果でないものは lint_accepted へ）',
    'octavo — build LaTeX / Typst / Beamer / Word from a Markdown manuscript.': 'octavo — マークダウンの原稿から LaTeX / Typst / Beamer / Word を作る。',
    'gathered {n} {n|file|files} into {path}': '{n} ファイルを {path} に集めた',
    'git': 'git',
    'gone': '無い',
    'hand-typed numbers': '直書きの数値',
    'how it runs': '実行環境',
    'if you deleted or renamed a .qmd, delete its .json too': '.qmd を消した／改名したなら、この .json も消す',
    'if you deleted or renamed the .qmd, delete this too (stale numbers keep reaching the text). If you wrote it by hand, leave it': '.qmd を消した／名前を変えたなら、このファイルも消す（古い数値が本文に入り続ける）。手で置いたものならそのままでよい',
    'in the text but with no value (left as they are):': '本文にあるのに値が無い（そのまま残る）:',
    'inserted': '挿入',
    'insertions only': '挿入だけ',
    'install it from https://github.com/typst/typst/releases (cargo works too)': 'https://github.com/typst/typst/releases から入れる（cargo でも可）',
    'is Settings -> Advanced -> "Allow other applications on this computer to communicate with Zotero" on?': '設定 → 詳細 →「他のアプリケーションとの通信を許可」が入っているか',
    'is Zotero running?': 'Zotero を起動しているか',
    'is the analysis (.qmd) up to date?': '分析 (.qmd) が最新かどうか',
    'it needs Zotero 7 or newer, with Settings -> Advanced -> "Allow other applications" turned on': 'Zotero 7 以降で、設定 → 詳細 →「他のアプリケーションとの通信を許可」が要る',
    'just one session': '1回分だけ',
    'keep luatexja / ltjsarticle in main.tex': 'main.tex の luatexja / ltjsarticle を外さないこと',
    'keep what it built': '作った一式を残す',
    'kept in: {path}': '置き場所: {path}',
    'kept: {path}': '残した: {path}',
    'latexmk': 'latexmk',
    'leave citations unresolved (a fast look at a draft)': '引用を解決しない（下書きを速く見たいとき）',
    'leave it as a folder instead of a zip': 'zip にせずフォルダで残す',
    'left alone': 'そのまま',
    'length': '分量',
    "list a coauthor's tracked changes": '共著者の赤入れを一覧にする',
    'list the output formats': '出せる形式の一覧',
    'list the references you cite': '引いている文献を一覧する',
    'list the registered manuscripts': '登録されている原稿の一覧',
    'ltjsarticle (texlive-lang-japanese)': 'ltjsarticle（texlive-lang-japanese）',
    'luatexja': 'luatexja',
    'machine-readable JSON': '機械可読な JSON',
    'made': '作った',
    'made {n} {n|file|files}': '{n} ファイル作った',
    'made {path}': 'できた: {path}',
    'make the post-acceptance replication package (a different set of files)': '受理後の複製パッケージを作る（中身が別物）',
    'manuscript': '原稿',
    'matches the record from {when} ({n} {n|file|files})': '{when} の記録と一致（{n} 件）',
    'missing: {what}': '足りない: {what}',
    'name': '名前',
    'newtheorem environments': 'newtheorem 環境',
    'next:': '次:',
    '{n} manual {n|one is|ones are} stale. octavo build does not run {n|it|them}: run {n|it|them} with octavo analysis run': '手動の {n} 本が古い。octavo build では走らないので、octavo analysis run で走らせる',
    'running {unit}…': '実行中: {unit}…',
    'manual': '手動',
    '{unit} is stale but runs only when asked (manual) — octavo analysis run {unit}': '{unit} は古いが、手動の指定なので自動では走らせない — octavo analysis run {unit}',
    'no registered analysis called {name}': '{name} という分析は登録されていない',
    'registered: {names}': '登録されているもの: {names}',
    'with run: only these .qmd (run even if not stale)': 'run と一緒に: この .qmd だけ（古くなくても走らせる）',
    'name a .qmd only with run: octavo analysis run {names}': '.qmd を名指しするのは run のときだけ: octavo analysis run {names}',
    'macOS: LuaLaTeX finds the system fonts itself': 'macOS: LuaLaTeX はシステムのフォントを自分で探す',
    'brew install pandoc': 'brew install pandoc',
    'MacTeX brings the Harano Aji fonts LaTeX uses: brew install --cask mactex-no-gui': 'LaTeX が使う原ノ味フォントは MacTeX に入っている: brew install --cask mactex-no-gui',
    'not needed on macOS': 'macOS では要らない',
    'brew install --cask font-biz-udgothic font-biz-udmincho font-inter': 'brew install --cask font-biz-udgothic font-biz-udmincho font-inter',
    'brew upgrade pandoc': 'brew upgrade pandoc',
    'brew install --cask mactex-no-gui (several GB; open a new terminal afterwards)': 'brew install --cask mactex-no-gui（数 GB。入れたらターミナルを開き直す）',
    'comes with MacTeX: brew install --cask mactex-no-gui': 'MacTeX に入っている: brew install --cask mactex-no-gui',
    'brew install typst': 'brew install typst',
    'brew upgrade typst': 'brew upgrade typst',
    'not needed with CSL. Only if you go back to biblatex: it comes with MacTeX': 'CSL なら不要。biblatex に戻すときだけ（MacTeX に入っている）',
    'comes with MacTeX (or set beamer_theme to default if you do not use it)': 'MacTeX に入っている（使わないなら beamer_theme を default に）',
    'brew install --cask font-noto-sans-cjk-jp font-noto-serif-cjk-jp. For a font kept elsewhere, point TYPST_FONT_PATHS at its folder': 'brew install --cask font-noto-sans-cjk-jp font-noto-serif-cjk-jp。別の場所のフォントを使うなら TYPST_FONT_PATHS にそのフォルダを',
    'referenced by {name}': '{name} が参照している',
    'output': '出力',
    'bibliography': '書誌',
    'there is no paper. Name the document to package (octavo bundle <name>)': '論文が無い。固める文書の名前を指定すること（octavo bundle <名前>）',
    'there is more than one paper. Name the one to package: octavo bundle <name>': '論文が複数ある。どれを固めるか指定すること: octavo bundle <名前>',
    'papers: {names}': '論文: {names}',
    'unknown output format: {name}': '知らない出力形式: {name}',
    'available: {names}': '使えるもの: {names}',
    'body word count': '本文の語数',
    'body character count': '本文の文字数',
    'abstract word count': '要旨の語数',
    'abstract character count': '要旨の文字数',
    ' words': '語',
    ' characters': '字',
    '{doc}: {what}': '{doc} の{what}',
    '(appendix)': '(付録)',
    "'ja' or 'en'": "'ja' か 'en'",
    "'csl' or 'native'": "'csl' か 'native'",
    "'16-9' or '4-3'": "'16-9' か '4-3'",
    'needed for CSL citation processing (--citeproc)': 'CSL による引用処理（--citeproc）に要る',
    'This list is **for reading**. Do not copy the docx back into the manuscript.': 'この一覧は**読むためのもの**。docx をそのまま原稿に戻さないこと。',
    'In the returned docx, {{n_obs}} is already the literal text "1,523";': '戻ってきた docx では {{n_obs}} が既に「1,523」という文字になっていて、',
    'writing it back pins the number into the manuscript (and breaks what this tool is for).': '書き戻すと数値の出所が原稿に固定される（このツールの前提が壊れる）。',
    'Make the edits in the .md, and change numbers in the .qmd.': '直すのは .md 側、数値を変えるなら .qmd 側。',
    'no year (shows as [n.d.])': '年がない（[n.d.] と出る）',
    'no author': '著者がない',
    'organization name split into surname and given name': '団体名が姓名に割れている',
    'no page range or DOI': 'ページも DOI もない',
    'no journal title': '掲載誌名がない',
    'no publisher': '出版社がない',
    'key contains characters that break typesetting': 'キーに組版で壊れる文字が入っている',
    'contains Japanese but has no langid': '日本語を含むのに langid が無い',
    'set Language to ja in Zotero': 'Zotero の Language を ja に',
    'needed to write {what}': '{what} の書き出しに要る',
    'main.typ must set a CJK font (check it is installed with: typst fonts)': 'main.typ が CJK フォントを設定していること（typst fonts で入っているか確認）',
    'Typst slides': 'Typst スライド',
    'Typst speaker script': 'Typst 台本',
    'Beamer slides': 'Beamer スライド',
    'LaTeX (LuaLaTeX)': 'LaTeX (LuaLaTeX)',
    'Word (.docx)': 'Word (.docx)',
    '({name} lives beside the manuscript; octavo new writes it if missing)': '（{name} は原稿の隣に置く。無ければ octavo new が作る）',
    'no BibTeX came back (check the Zotero version and settings)': 'BibTeX が返ってこなかった（Zotero の版と設定を確認）',
    'no _session in the value files': '値のファイルに _session が無い',
    'no analysis is registered. Write this in octavo.config.py:': '分析は登録されていない。octavo.config.py に次を書く:',
    'no collection called {name}.': 'コレクション {name} が無い。',
    'no config file at {path}': '設定ファイルが無い: {path}',
    'no documents registered. Add one with e.g. octavo new paper <name>': '文書が登録されていない。octavo new paper <名前> などで足す',
    'no documents to build. Add a manuscript with octavo new paper|slides|lecture <name>, or write it into documents in octavo.config.py': '作る文書が無い。octavo new paper|slides|lecture <名前> で原稿を足すか、octavo.config.py の documents に書くこと',
    'no fc-list, so this cannot be checked': 'fc-list が無いので確認できない',
    'no locale set': 'ロケール未設定',
    'no manuscript at {path}': '原稿が無い: {path}',
    'no marks left': '印は残っていない',
    'no output at {dir} (run octavo build --to {target} first)': '出力が無い: {dir}（先に octavo build --to {target}）',
    'no placeholders left': '仮の図は残っていない',
    'no quarto, so {units} cannot be run. The numbers in {dir}/ may be stale (octavo doctor says how to install it)': 'quarto が無いので {units} を走らせられない。{dir}/ の数値は古いままかもしれない（入れ方は octavo doctor）',
    "no reference document at {path} — pandoc's default look it is": '雛形が見つからない: {path} — pandoc の既定の見た目になる',
    'no sign this was built anonymously. Run octavo build --anonymous --to <format> first': '匿名で組んだ跡が無い。先に octavo build --anonymous --to <形式> を走らせること',
    'no such file: {path}': 'ファイルが無い: {path}',
    'no tracked changes and no comments': '変更履歴もコメントも見つからなかった',
    'no typst, so this cannot be checked': 'typst が無いので確認できない',
    'no {cmd}, so it was skipped': '{cmd} が無いので飛ばした',
    'no {pattern} in {dir} (run octavo build {doc} --to {target} first)': '{dir} に {pattern} が無い（先に octavo build {doc} --to {target}）',
    'none found': '見つからない',
    'none of the numbers the text prints have changed': '本文に出る数字は変わっていない',
    'not found': '見つからない',
    'not found (only needed if the .qmd is R)': '見つからない（.qmd を R で書くときだけ要る）',
    'not found (only needed to run a .qmd)': '見つからない（.qmd を走らせるときだけ要る）',
    'not found (see octavo doctor)': '見つからない（octavo doctor 参照）',
    'not found: {unit}': '見つからない: {unit}',
    'not needed with CSL. Only if you go back to biblatex: sudo apt install biber': 'CSL 運用では要らない。biblatex に戻すときだけ sudo apt install biber',
    'not one `::: notes` — this is just the deck on paper': '`::: notes` が1つも無い。スライドと同じ中身だけの紙になる',
    'not recorded': '記録に無い',
    'note': '注意',
    'nothing fatal ({n} to look at)': '致命的な問題は無い（注意 {n} 件）',
    'nothing recorded ({n} {n|file|files} under data/)': '記録が無い（data/ に {n} 件）',
    'nothing to compare with. Run octavo analysis run once and the values from just before are kept as the reference': '比べる相手が無い。octavo analysis run を1度走らせると、その直前の値が控えとして残る',
    'nothing to connect to': '接続先が無い',
    'nothing wrong': '問題なし',
    'one audit before submitting': '投稿前にまとめて検査する',
    'output formats: {list} / all / print. Several, comma-separated': '出力形式: {list} / all / print。コンマ区切りで複数',
    'overwrite files that are already there': '既存のファイルも上書きする',
    'p value': 'p 値',
    'packed {n} {n|file|files} into {path} ({size} bytes)': '{n} ファイルを {path} に固めた（{size} bytes）',
    'pandoc': 'pandoc',
    'pandoc 2.11+ (CSL citations)': 'pandoc 2.11+（CSL 引用）',
    'pandoc 3.1+ (Typst output)': 'pandoc 3.1+（Typst 書き出し）',
    'pandoc failed:': 'pandoc が失敗した:',
    'pandoc not found.': 'pandoc が見つからない。',
    'pandoc {need} or newer is required (this is {got})': 'pandoc {need} 以上が要る（いま {got}）',
    "pandoc's built-in chicago-author-date is used (no .csl file)": 'pandoc 内蔵の chicago-author-date を使う（.csl ファイルは無し）',
    "pandoc's default (chicago-author-date)": 'pandoc 既定 (chicago-author-date)',
    'paper=a paper / slides=talk slides / lecture=lecture notes (an A4 handout + a deck per session)': 'paper=論文 / slides=発表スライド / lecture=講義ノート（A4 プリント + 回ごとのスライド）',
    'paragraph {n}': '段落 {n}',
    'percentage': 'パーセント',
    'placeholder values': '仮の値',
    'print every detail': '内訳を全部出す',
    'print one line of machine-readable JSON (for the VS Code extension and friends)': '機械可読な JSON で1行出す（VS Code 拡張などが読む）',
    'print the results as machine-readable JSON (including where the PDF landed)': '結果を機械可読な JSON で出す（できた PDF の場所を含む）',
    'profiles:': 'プロファイル:',
    'put data/raw in the --replication package too (check it may be shared)': '--replication に data/raw も入れる（再配布可か確かめて）',
    'ran {unit} ({secs}s)': '走らせた: {unit}（{secs} 秒）',
    'raw data': '原データ',
    "read a coauthor's tracked changes out of a .docx": '共著者が返してきた .docx の赤入れを見る',
    'rebuild whenever a manuscript is saved': '原稿を保存するたびに作り直す',
    'record / check the data fingerprints': 'データの指紋を記録する／確かめる',
    'recorded but gone': '記録にあるが無い',
    'rename one of the manuscripts (or its folder)': 'どちらかの原稿（か、そのフォルダ）の名前を変えること',
    'repackage it for a submission system': '投稿システムに上げる形に固め直す',
    'repackage it for submission': '投稿用に固め直す',
    'replace them with your own content, comment mark and all': '自分の内容に置き換えて、印のコメントごと消す',
    'results go in: {path}': '結果の置き場: {path}',
    'results_dir is outside the repository, so it cannot be compared with git': 'results_dir がリポジトリの外にあるので git と比べられない',
    'run it again even if it is not stale': '古くなくても走らせ直す',
    'run the .qmd again even if it is not stale': '古くなくても .qmd を走らせ直す',
    'run the analysis (.qmd)': '分析（.qmd）を走らせる',
    'run the analysis with octavo analysis run — as it is, the numbers that get typeset are fake': 'octavo analysis run で分析を走らせる（いまのままでは嘘の数字が組まれる）',
    'run the analysis with octavo analysis run, and check the spelling of the names': 'octavo analysis run で分析を走らせる。名前の綴りも確かめる',
    'run the stale .qmd through quarto': '古い .qmd を quarto で走らせる',
    'running the analysis once records it (for the replication package)': '分析を1度走らせると記録される（replication package 用）',
    'sample size': '標本サイズ',
    'see whether the tools are there': '環境が足りているか見る',
    'self-citations': '自己引用',
    'show the heading structure': '原稿の見出し構成を見る',
    'skipped: needs pandoc {ver} or newer': '飛ばす: pandoc {ver} 以上が要る',
    'something changed, rebuilding': '変わったので作り直す',
    'something is missing, clashing, or not anonymised. Fix what is above before submitting': '欠落・衝突・匿名化の漏れがある。上を見て直してから投稿すること',
    'stale': '古い',
    'status=check against the record (default) / hash=write the record': 'status=記録と食い違わないか（既定） / hash=記録する',
    'status=see whether it is up to date (default) / run=run it': 'status=最新かどうか見る（既定） / run=走らせる',
    'stopped': '止めた',
    'style IDs are listed at https://www.zotero.org/styles': 'スタイル ID は https://www.zotero.org/styles で確認できる',
    'substituted {n}': '{n} 個を差し込んだ',
    'sudo apt install fontconfig': 'sudo apt install fontconfig',
    'sudo apt install fonts-noto-cjk (then fc-cache -f). For a font kept elsewhere, point TYPST_FONT_PATHS at its folder': 'sudo apt install fonts-noto-cjk（入れた後 fc-cache -f）。別の場所のフォントなら TYPST_FONT_PATHS でそのフォルダを指す',
    'sudo apt install fonts-noto-cjk fonts-noto-cjk-extra': 'sudo apt install fonts-noto-cjk fonts-noto-cjk-extra',
    'sudo apt install latexmk': 'sudo apt install latexmk',
    'sudo apt install pandoc (if it is old, take the .deb from GitHub)': 'sudo apt install pandoc（古ければ GitHub の .deb を入れる）',
    'sudo apt install texlive-lang-japanese': 'sudo apt install texlive-lang-japanese',
    'sudo apt install texlive-latex-extra (or set beamer_theme to default if you do not use it)': 'sudo apt install texlive-latex-extra（使わないなら beamer_theme を default に）',
    'sudo apt install texlive-latex-recommended': 'sudo apt install texlive-latex-recommended',
    'sudo apt install texlive-luatex texlive-lang-japanese': 'sudo apt install texlive-luatex texlive-lang-japanese',
    'table files': '表のファイル',
    'take a newer .deb from https://github.com/jgm/pandoc/releases': 'https://github.com/jgm/pandoc/releases から新しい .deb を入れる',
    'talk to Zotero': 'Zotero との受け渡し',
    'template leftovers': 'ひな型の残り',
    'that name will not do: {name} (no spaces, no / or \\, and it cannot start with a dot)': 'この名前は使えない: {name}（空白・/・\\ を含まず、. で始まらない名前にする）',
    'the .docx that came back': '戻ってきた .docx',
    'the A4 handout, through to PDF': 'A4 プリントを PDF まで',
    'the CJK font in typst_slides_font must be installed (check with: typst fonts)': 'typst_slides_font の日本語フォントが入っていること（typst fonts で確認）',
    'the CSL style {id} is not here.': 'CSL スタイル {id} がローカルに無い。',
    'the Zotero local API is unavailable ({why}).': 'Zotero のローカル API が使えない（{why}）。',
    'the analysis failed. Building around stale numbers would contradict the text, so this stops here.': '分析が失敗した。数値が古いまま変換すると本文と食い違うので止める。',
    'the analysis has never run: {files} {n|is|are} the starter values octavo init wrote': '分析を1度も走らせていない: {files} は octavo init が置いた仮の値',
    'the bibliography is unreadable or empty: {path}': '書誌が読めない、または空: {path}',
    'the cache is empty. Fetch one with e.g. octavo csl get apa': 'キャッシュは空。octavo csl get apa などで取れる',
    'the document name (it becomes the file or folder name)': '文書の名前（ファイル名・フォルダ名になる）',
    "the journal's style (CSL)": '雑誌の書式（CSL スタイル）',
    'the slides, one PDF per session': 'スライドを回ごとに PDF まで',
    'the slides, through to PDF': 'スライドを PDF まで',
    'the style to try': '試す書式',
    'then edit draft and bib_file in it.': 'として作り、draft や bib_file を書き換えること。',
    'there is: {names}': 'ある: {names}',
    'there was no data/HASHES.json, so it was written': 'data/HASHES.json が無かったので作った',
    'these are real values': '本物の値が入っている',
    'this is the main.* arrangement, so --compile does not typeset it ({next})': 'main.* 方式なので --compile では組まない（{next}）',
    'main.tex does not define the CSLReferences environment the bibliography uses — octavo template copy paper/csl-preamble.tex has the definition': 'main.tex に、書誌が使う CSLReferences 環境の定義が無い — 定義は octavo template copy paper/csl-preamble.tex にある',
    'to mark a version, tag it: git tag v1-submitted': '版を刻むには git tag を打つ: git tag v1-submitted',
    'to place it by hand: {path}': '手で置く場合: {path}',
    'total (without duplicates): {n}': '合計（重複を除く）: {n} 件',
    'treat warnings as failures too (for CI)': '注意も失敗として扱う（CI 向け）',
    'two documents share the name {name}': '文書の名前がぶつかっている: {name}',
    'two files share the name {name} ({a} and {b}) — rename one': '同じ名前のファイルが2つある: {name}（{a} と {b}）— 片方を改名すること',
    'typeset it as well (latexmk / typst compile)': '組版まで走らせる（latexmk / typst compile）',
    'typeset main.typ through to PDF': 'main.typ を組んで PDF まで',
    'typst': 'typst',
    'unknown formats in figure_ext: {names}': 'figure_ext に知らない形式: {names}',
    'unknown formats in out_dirs: {names}': 'out_dirs に知らない形式: {names}',
    'unknown kind: {kind} (one of {allowed})': '知らない種類: {kind}（{allowed}）',
    'unresolved {ref} — not reachable from the output ({dir}/)': '参照不能 {ref} — 出力（{dir}/）から辿れない',
    'upgrade Typst (octavo setup installs the version this was tested on)': 'Typst を上げる（octavo setup が動作を確かめた版に入れ直す）',
    'upgrade to pandoc 2.11 or newer (CSL citations need it)': 'pandoc 2.11 以上に上げる（CSL 引用に必須）',
    'upgrade to pandoc 3.1 or newer': 'pandoc 3.1 以上に上げる',
    'using the styles from {file}': '雛形 {file} のスタイルを使う',
    'value files': '値のファイル',
    'value files with no matching .qmd:': '対応する .qmd が無い値のファイル:',
    'values nothing uses:': '使っていない値:',
    'warning: unknown keys in the config (ignored): {keys}': '警告: 設定に知らないキーがある（無視する）: {keys}',
    'watch the manuscripts and rebuild': '原稿の変更を見て作り直す',
    'watching: {files}': '見張る: {files}',
    'what came back is not a CSL (check the ID)': '取れたものが CSL ではない（ID の綴りを確認）',
    'what changed since the analysis last ran; pass a git tag or commit to compare with that version': '前に分析を走らせたときからの変化。git のタグやコミットを渡すとその版と比べる',
    'what moved since last time (or a git version)': '前回（か git の版）からの数値の変化',
    'where octavo.config.py is (default: here)': 'octavo.config.py の場所（既定: カレント）',
    'where to write it (default: bib_file from the config)': '書き出し先（既定: config の bib_file）',
    'where to write it (default: submission-<name>.zip)': '出力先（既定: submission-<名前>.zip）',
    'which paper to pack (you can leave this out if there is only one)': '固める論文の名前（論文が1本だけなら省略できる）',
    'within the limits': '規定の範囲に収まっている',
    "without Word's Track Changes on, edits leave no trace": 'Word の「変更履歴の記録」が入っていないと、直した跡は残らない',
    'words (without/with tables): {excl} / {incl}   characters (without spaces): {chars}': '語数（表除く/含む）: {excl} / {incl}\u3000文字数（空白等除く）: {chars}',
    'working in: {path}': '作業場所: {path}',
    "write  'csl': '{id}',  in octavo.config.py": "octavo.config.py に  'csl': '{id}',  と書く",
    'write a Word reference .docx': 'Word の雛形 .docx を作る',
    'write a project skeleton': 'プロジェクトのひな型を作る',
    'write a project skeleton (add manuscripts with octavo new)': 'プロジェクトのひな型を作る（原稿は octavo new で足す）',
    'wrote {n} {n|entry|entries} to {path} (from {source})': '{n} 件を {path} に書いた（{source}）',
    '{files} {n|is|are} still the starter values octavo init wrote.': '{files} は octavo init が置いたひな型のまま。',
    '{file} has no `#` headings, so the slides cannot be split by session': '{file} に `#` 見出しが無いのでスライドを回ごとに分けられない',
    '{file} has no session {part} (the `#` heading is gone, or its {{#id}} changed)': '{file} に「{part}」の回が無い（`#` 見出しが消えたか、{{#id}} が変わった）',
    '{file} is not a dictionary (ignored)': '{file} の中身が辞書でない（無視する）',
    '{file} is still the starter values octavo init wrote. The numbers in the text are fake (octavo analysis run makes them real)': '{file} は octavo init が置いた仮の値のまま。本文の数字は嘘（octavo analysis run で本物にする）',
    '{file} switches on {guard}, so it does not reach the typeset output. But **{needle} is still in the source file** — delete it if the journal wants the .tex itself': '{file} は {guard} で切り替えているので組版には出ない。ただし**原稿ファイルの中には「{needle}」が残る** — .tex ごと出す雑誌なら消すこと',
    '{id} is a dependent style -> fetching its parent {parent}': '{id} は従属スタイル -> 親 {parent} を取る',
    '{key} must be a list (got {got})': '{key} はリストで書く（いま {got}）',
    '{key} must be {allowed} (got {got})': '{key} は {allowed}（いま {got}）',
    '{label} {n}:': '{label} {n} 件:',
    '{label}: {got}{unit} (limit {limit}{unit}, over by {excess}{unit})': '{label}: {got}{unit}（上限 {limit}{unit}、超過 {excess}{unit}）',
    '{lines} {lines|line|lines} of text / {files} table {files|file|files} — {hint}': '本文 {lines} 行 / 表 {files} ファイル — {hint}',
    '{name} is in both {first} and {second} ({second} wins)': '{name} が {first} と {second} の両方にある（{second} を採る）',
    '{name} is not in {dir}/ (left as it is)': '{name} が {dir}/ に無い（そのまま残した）',
    '{needle} is still in {file} (guard it with {guard}, or delete it by hand)': '{file} に「{needle}」が残っている（{guard} で囲むか、手で消すこと）',
    '{n} {n|is|are} in the .bib but never cited ({n|it does|they do} not reach the output)': '.bib にあって引いていないもの {n} 件（残っていても組版には出ない）',
    '{n} {n|is|are} over the limit': '{n} 件が規定を超えている',
    '{n} {n|is|are} stale. Run {n|it|them} with octavo analysis run (octavo build runs {n|it|them} too)': '{n} 本が古い。octavo analysis run で走らせる（octavo build でも自動で走る）',
    '{n} {n|is still a placeholder|are still the placeholders} octavo init wrote': '{n} 件が octavo init の仮の図のまま',
    '{n} cached': '{n} 件キャッシュ済み',
    '{n} {n|candidate|candidates}': '候補 {n} 件',
    '{n} {n|change|changes} in {paras} {paras|paragraph|paragraphs}': '{n} 件（{paras} 段落）',
    '{n} {n|citation|citations}': '引用 {n} 件',
    '{n} {n|differs|differ} from the record': '記録と違う {n} 件',
    '{n} {n|difference|differences}:': '食い違い {n} 件:',
    '{n} {n|entry|entries}': '{n} 件',
    '{n} failed': '失敗 {n} 件',
    '{n} {n|family|families}': '{n} 系統',
    '{n} fatal. Typesetting this would be wrong': '致命的 {n} 件。このままでは組んでも間違う',
    '{n} found': '{n} 件',
    '{n} {n|frame|frames}': 'frame {n} 枚',
    '{n} {n|frame looks|frames look} likely to overflow (over {limit} lines) — split {n|it|them}, or use a smaller font': '中身が多すぎて枠から溢れそうな frame が {n} 枚（{limit} 行超）— 分けるか小さめのフォントを検討',
    '{n} octavo:example {n|mark|marks}': 'octavo:example の印が {n} 箇所',
    '{n} {n|key is|keys are} not in the .bib': '.bib に無いキー {n} 件',
    '{n} {n|key is|keys are} not in the .bib — {n|it typesets|they typeset} as ??': '.bib に無いキー {n} 件 — 組版で ?? になる',
    '{n} {n|looks like a hand-typed number|look like hand-typed numbers} (if {n|it is a result, move it|they are results, move them} to ov_value() in the .qmd)': '直書きされた数値らしきもの {n} 件（分析結果なら .qmd の ov_value() に移す）',
    '{n} missing': '無い {n} 件',
    '{n} missing — typesetting will fail as it is': '{n} 件足りない — このまま組版すると落ちる',
    '{n} {n|pair looks|pairs look} like the same reference twice': '同じ文献が二重に入っていそう {n} 組',
    '{n} {n|place is|places are} still the template (replace {n|it|them} with your own content and delete the octavo:example {n|mark|marks})': 'ひな型のままの箇所 {n} 件（自分の内容に置き換えて octavo:example の印ごと消す）',
    '{n} possible {n|self-citation|self-citations}: {keys} (whether to mask {n|it|them} depends on the journal)': '自己引用の候補 {n} 件: {keys}（伏せるかどうかは雑誌の規定で判断すること）',
    '{n} {n|reference points|references point} nowhere — typesetting will fail as it is': '指し先を解決できない参照 {n} 件 — このまま組版すると落ちる',
    '{n} {n|slide|slides} (title and section slides not counted)': '{n} 枚（題扉・節の扉を除く）',
    '{n} to deal with': '要対応 {n} 件',
    '{n} to look at': '要注意 {n} 件',
    '{n} unresolved': '未解決 {n} 件',
    '{n} {n|value|values} changed:': '変わった値 {n} 件:',
    '{n} {n|value|values} in {path} ({files} {files|file|files})': '{path} の値 {n} 個（{files} ファイル）',
    '{n} with no matching .qmd': '対応する .qmd が無いもの {n} 件',
    '{n} — fix {n|it|them} in Zotero and export again': '{n} 件 — Zotero 側で直して書き出し直す',
    '{n} — listed in bib_accepted as not worth fixing': '{n} 件 — bib_accepted で直さないと決めたもの',
    '{path} has no CONFIG dictionary': '{path} に CONFIG 辞書が無い',
    '{slides} {slides|slide|slides} / {notes} {notes|note|notes}': 'スライド {slides} 枚 / ノート {notes} 個',
    '{stale} of {n} {stale|is|are} stale': '{n} 本中 {stale} 本が古い',
    '{values} {values|value|values} in {files} {files|file|files}': '値 {values} 個 / ファイル {files} 個',
    '{who}: {n}': '{who}: {n} 件',
    '{{…}} in the text': '本文の {{…}}',
    '— fetch one with e.g. octavo csl get apa': '— octavo csl get apa などで取れる',
    '— set OCTAVO_LANG=ja for Japanese': '— 日本語にするなら OCTAVO_LANG=ja',
    '… and {n} more': '… 他 {n} 件',
    '…and {n} more (--verbose for all of them)': '…ほか {n} 件（--verbose で全部）',
    'installed': '入っている',
    'not installed': '入っていない',
    '      └ renv': '      └ renv',
    ' none ': ' 不足 ',
    'all there: {names}': '揃っている: {names}',
    'missing: {names} (a fallback font is used instead)': '無い: {names}（代わりのフォントで組む）',
    '  └ default typefaces': '  └ 既定の書体',
    'For the default typefaces:': '既定の書体を入れるなら:',
    'sudo apt install fonts-morisawa-bizud-gothic fonts-morisawa-bizud-mincho fonts-inter (then fc-cache -f)': 'sudo apt install fonts-morisawa-bizud-gothic fonts-morisawa-bizud-mincho fonts-inter（入れた後 fc-cache -f）',
    'show or change the common settings': 'よく使う設定を見る・変える',
    'usage: octavo config set KEY VALUE / octavo config unset KEY': '使い方: octavo config set 鍵 値 / octavo config unset 鍵',
    '{key} = {value}  ({path})': '{key} = {value}  （{path}）',
    '(default)': '（既定）',
    'Language of the documents': '文書の言語',
    'Citation style (CSL ID or alias)': '引用の書式（CSL の ID か別名）',
    'Aspect ratio': '縦横比',
    'Accent colour': '差し色',
    'Section name in the top-left corner': '左上の節名',
    'Divider slide for each section': '節ごとの扉',
    'Heading numbers': '見出しの番号',
    'Word limit (text)': '語数の上限（本文）',
    'Character limit (text)': '文字数の上限（本文）',
    'Word limit (abstract)': '語数の上限（要旨）',
    'Character limit (abstract)': '文字数の上限（要旨）',
    'Documents': '文書',
    'Slides': 'スライド',
    'Submission limits': '投稿規定',
    '{key} cannot be changed from here — edit octavo.config.py': '{key} はここからは変えられない。octavo.config.py を直すこと',
    '{key} cannot be empty': '{key} は空にできない',
    '{key} takes true or false': '{key} は true か false',
    '{key} takes a whole number': '{key} は正の整数',
    '{key} takes one of {allowed}': '{key} は {allowed} のどれか',
    '{key} spans several lines in octavo.config.py — edit it by hand': '{key} は octavo.config.py で複数行にまたがっている。手で直すこと',
    'could not find the end of CONFIG in octavo.config.py': 'octavo.config.py の CONFIG の終わりが見つからない',
    'the result is not a valid config': '書き換えると設定として読めなくなる',

    # ---- octavo template -------------------------------------------------
    'list, copy or compare the templates you can override': '上書きできるひな型の一覧・写し・同梱との差分',
    'the template, e.g. slides/typst-slides.typ': 'ひな型の名前（例: slides/typst-slides.typ）',
    'copy it for all your projects (~/.config/octavo/templates)': '自分の全プロジェクト用に写す（~/.config/octavo/templates）',
    'which templates are in use, and how to make your own': 'どのひな型が効いているか・自分用の作り方',
    'not a template name: {name}': 'ひな型の名前として読めない: {name}',
    'this project': 'このプロジェクト',
    'yours': 'あなたの',
    'Looked for in this order (the first one found is used):': 'この順に探し、最初に見つかったものを使う:',
    'Start your own with octavo template copy <name> [--user].': '自分用は octavo template copy <名前> [--user] で作り始める。',
    'which template? (octavo template list shows them)': 'どのひな型か（octavo template list で一覧が出る）',
    'no bundled template called {name} (octavo template list shows them)': '{name} という同梱のひな型は無い（octavo template list で一覧が出る）',
    'not inside a project (no octavo.config.py here) — add --user to copy it for all your projects': 'プロジェクトの中ではない（octavo.config.py が無い）— 全プロジェクト用に写すなら --user を付ける',
    '{path} is already there (--force overwrites it)': '{path} はもうある（--force で上書き）',
    'wrote {path} — edit it; it is used instead of the bundled one': '{path} に写した。これを直せば、同梱のものの代わりにこちらが使われる',
    '{name} is not overridden — the bundled one is in use': '{name} は上書きされていない（同梱のものを使っている）',
    '{path} is the same as the bundled one': '{path} は同梱のものと同じ',
    'keep luatexja-preset in the Beamer header (templates/slides/beamer-header-ja.tex)': 'Beamer のヘッダーに luatexja-preset を残すこと（templates/slides/beamer-header-ja.tex）',

    # ---- octavo release --------------------------------------------------
    'tag this version and put its PDF on a GitHub Release': 'この版にタグを打ち、PDF を GitHub Release に置く',
    'tag this version, PDF to a GitHub Release': 'この版にタグ、PDF を GitHub Release へ',
    'the document name': '文書の名前',
    'what this version is, e.g. v1-submitted (the tag becomes <document>-<label>)': '何の版か。例: v1-submitted（タグは <文書>-<ラベル> になる）',
    "formats (default: the document's targets)": '形式（既定は文書の targets）',
    'check and build, but tag, push and upload nothing': '確認と組版だけして、タグ・push・アップロードはしない',
    'git is not installed': 'git が入っていない',
    'this project is not a git repository (git init, then commit)': 'このプロジェクトは git のリポジトリではない（git init してコミットする）',
    'no document called {name}': '{name} という文書は無い',
    'documents: {names}': 'ある文書: {names}',
    '(none)': '（なし）',
    'to add a manuscript: octavo new paper|slides|lecture <name>': '原稿を足すなら: octavo new paper|slides|lecture <名前>',
    '{tag} cannot be a git tag name': '{tag} は git のタグ名にできない',
    'the tag {tag} already exists': 'タグ {tag} はもうある',
    'there are uncommitted changes — commit them first, so the tag points at what gets typeset:': 'コミットしていない変更がある。先にコミットする（タグが組版したものを指すように）:',
    'the analysis values are still the placeholders octavo init wrote — run the analysis first': '分析の値が octavo init の置いた仮の値のまま。先に分析を走らせる',
    'the analysis is stale ({files}) — run octavo analysis run, commit results/, then release': '分析が古い（{files}）。octavo analysis run のあと results/ をコミットしてから出す',
    'there is no remote called origin to push the tag to': 'タグを push する先（origin）が無い',
    'the GitHub CLI (gh) is not installed: https://cli.github.com/ (then gh auth login)': 'GitHub CLI（gh）が入っていない: https://cli.github.com/（入れたら gh auth login）',
    'gh is not logged in (gh auth login)': 'gh にログインしていない（gh auth login）',
    'not released:': '出さなかった:',
    'not released: the build failed': '出さなかった: 組版に失敗した',
    'not released: nothing was typeset to attach (no PDF or Word file)': '出さなかった: 添付するもの（PDF か Word）が組み上がっていない',
    'tag {tag} on {sha}, with:': 'タグ {tag}（{sha}）に添付するもの:',
    '(dry run — nothing tagged, pushed or uploaded)': '（試しに組んだだけ。タグ・push・アップロードはしていない）',
    'the tag was made here but not pushed: git push origin {tag}': 'タグは手元に打ったが push できなかった: git push origin {tag}',
    'the tag {tag} is pushed, but the release was not made. Run octavo release again after deleting the tag (git tag -d {tag} && git push origin :refs/tags/{tag}), or attach the files by hand with gh release create': 'タグ {tag} は push したが、Release は作れなかった。タグを消してから octavo release をやり直す（git tag -d {tag} && git push origin :refs/tags/{tag}）か、gh release create で手で添付する',

    # ---- octavo selftest の判定 -------------------------------------------
    'frames are made': 'frame ができている',
    'the look template is in': '体裁のテンプレートが入っている',
    'the analysis values are filled in': '分析の数値が差し込まれている',
    'the figure is in, with its label': '図がラベルつきで入っている',
    'the figure, table and equation carry their labels': '図・表・式にラベルが付いている',
    'the labelled equation is numbered': 'ラベルのある式に番号が付く',
    'numbers are written in (Word does not number)': '番号が文字で入っている（Word は番号を振らない）',
    'citations are resolved by CSL': '引用が CSL で解決されている',
    'citations are resolved': '引用が解決されている',
    'the Japanese text is there': '日本語が入っている',
    'the bibliography is there': '書誌一覧が出ている',
    'the speaker notes are kept': '発表者ノートが残っている',
    'the speaker notes are dropped': '発表者ノートが落ちている',
    'cross-references are #ref(<label>)': '相互参照が #ref(<label>) になっている',
    'cross-references are \\ref': '相互参照が \\ref になっている',
    'citation in the text': '地の文の引用',
    'Japanese citation': '日本語の引用',
    'organization as author': '団体著者',
    '(cannot read it: {error})': '(読めない: {error})',
    # 道具を入れる（octavo setup）・プロジェクトの環境（octavo env）
    '  └ uv (Python)': '  └ uv（Python）',
    'not found (sets up .venv for a Python .qmd)': '無い（Python の .qmd に使う .venv を作る）',
    'For the analysis ({what}): {cmd}': '分析に使うもの（{what}）: {cmd}',
    'install the tools (pandoc, Typst, quarto, R, uv, fonts)': '道具を入れる（pandoc・Typst・quarto・R・uv・フォント）',
    "set up this project's .venv and renv": 'このプロジェクトの .venv と renv を用意する',
    'TeX Live too (several GB)': 'TeX Live も入れる（数 GB）',
    'leave out quarto': 'quarto を入れない',
    'leave out R': 'R を入れない',
    'only show what would be installed': '何を入れるか見るだけ',
    'setup.sh or bash is missing, so this cannot run here': 'setup.sh か bash が無いので、ここでは動かせない',
    '.venv is already there': '.venv はもうある',
    'requirements.txt lists nothing yet: add a package there, then run this again': 'requirements.txt にはまだ何も書いていない。パッケージを書いたら、もう一度これを走らせる',
    'uv is not installed, so this was skipped. octavo setup installs it': 'uv が無いので飛ばした。octavo setup が入れる',
    'R is not installed, so this was skipped. octavo setup installs it': 'R が無いので飛ばした。octavo setup が入れる',
    'Something failed (see above). Fix it and run octavo env again.': 'うまくいかなかったものがある（上を見る）。直してから octavo env をもう一度',
    'Neither uv nor R is installed. Run octavo setup first.': 'uv も R も無い。先に octavo setup を',
    'Windows: LuaLaTeX finds the system fonts itself': 'Windows: LuaLaTeX はシステムのフォントを自分で探す',
    'On Windows, octavo setup does not install TeX. Install MiKTeX or TeX Live yourself if you need LaTeX / Beamer.': 'Windows では octavo setup は TeX を入れない。LaTeX / Beamer が要るなら MiKTeX か TeX Live を自分で入れる',
    'setup.ps1 is missing, so this cannot run here': 'setup.ps1 が無いので、ここでは動かせない',
    'the analysis environment (.venv and renv)': '分析の環境（.venv と renv）',
    'The analysis environment is ready. Commit requirements.txt and renv.lock.': '分析の環境ができた。requirements.txt と renv.lock を commit する',
    # 相互参照（crossref.py）
    'write the label on the figure, table, equation or heading: {example}': '図・表・式・見出しにラベルを付ける: {example}',
    'every table from the analysis is there': '分析の表はすべてある',
    'cross-references': '相互参照',
    '{path} is missing (octavo analysis run, or ov_table() in the .qmd)': '{path} が無い（octavo analysis run か、.qmd の ov_table()）',
    '{n} {n|label is|labels are} used twice': '{n} 個のラベルが2回使われている',
    'no such {n|label|labels}: {names} (written as ??)': '無いラベル: {names}（?? と書いた）',
    '{n} {n|reference points|references point} at no label': '{n} か所の参照の先にラベルが無い',
    'octavo analysis run (ov_figure() / ov_table() in the .qmd rewrite them)': 'octavo analysis run（.qmd の ov_figure() / ov_table() が書き直す）',
    'every labelled figure, table and equation is referred to': 'ラベルを付けた図・表・式はどれも参照されている',
    '{n} {n|figure, table or equation is|figures, tables or equations are} never referred to': '{n} 個の図・表・式がどこからも参照されていない',
    'placeholder figures and tables': '仮の図・表',
    'unused labels': '使われていないラベル',
    'refer to it with @label, or drop the label': '@ラベル で参照するか、ラベルを外す',
    'the label {label} is used twice': 'ラベル {label} が2回使われている',
    'every @fig- / @tbl- / @eq- / @sec- has its label': '@fig- / @tbl- / @eq- / @sec- の参照先はすべてある',
}
