# -*- coding: utf-8 -*-
"""CLI が画面に出す文字列の日本語。

鍵は `i18n.t()` に渡す**英語の原文そのまま**。原文を直したら、ここの鍵も
直すこと（直し忘れは英語のまま出るだけで落ちない）。
`Messages::test_every_message_has_a_japanese_translation` が、コードの中の
`t('…')` とこの表の過不足を突き合わせる。

埋め込みは `{name}` の名前つき。順番は変えてよいが、**名前は原文と同じもの**
を使うこと（`i18n.t` は渡された名前しか差し替えない）。
"""
from __future__ import annotations

MESSAGES: dict = {
    # -- レポート行の頭の印（i18n.tag）--------------------------------
    '[CJK]': '[日本語]',
    '[Word]': '[Word]',
    '[abstract]': '[要旨]',
    '[accepted]': '[許容済み]',
    '[analysis]': '[分析]',
    '[anonymous]': '[匿名]',
    '[assets]': '[素材]',
    '[bib flaws]': '[書誌の不備]',
    '[bib]': '[書誌]',
    '[careful]': '[要注意]',
    '[clash]': '[衝突]',
    '[conditional]': '[条件付き]',
    '[crossref]': '[相互参照]',
    '[fatal]': '[致命的]',
    '[figure]': '[図]',
    '[layout]': '[体裁]',
    '[length]': '[分量]',
    '[missing]': '[欠落]',
    '[note]': '[注意]',
    '[placeholder]': '[仮の値]',
    '[replication]': '[再現用]',
    '[script]': '[台本]',
    '[slides]': '[スライド]',
    '[split]': '[分割]',
    '[stopped]': '[中止]',
    '[table]': '[表]',
    '[typeset]': '[組版]',
    '[unused]': '[未使用]',
    '[values]': '[値]',
    '[warning]': '[警告]',
    '[wrote]': '[書いた]',

    # -- 画面に出す文言 ------------------------------------------------
    # 固有名詞とコマンドは訳しようがないので原文のまま載せている
    '  ok  ': '  ok  ',
    '  └ CSL citations': '  └ CSL 引用',
    '  └ R (Rscript)': '  └ R (Rscript)',
    '  └ Typst output': '  └ Typst 出力',
    '  └ visible to Typst': '  └ Typst から見えるか',
    ' / {n} duplicate {n|pair|pairs}': '／重複 {n} 組',
    ' note ': ' 注意 ',
    '(already there)': '（既にある）',
    '(lines {a}-{b})': '（{a}-{b} 行）',
    '(make sure this data may be redistributed)': '（再配布してよいデータか、必ず確かめること）',
    '(no bibliography list)': '（一覧は出さない）',
    '(no manuscript)': '（原稿がない）',
    '(put the raw data in data/raw/ and say where it came from in data/raw/README.md)': '（data/raw/ に原データを置き、data/raw/README.md に出所を書く）',
    'add an appendix later': '付録を後から足す',
    'add main.tex, to typeset with LaTeX': 'LaTeX で組むなら main.tex を足す',
    '--appendix and --tex are for papers only': '--appendix と --tex は論文（paper）にだけ使える',
    'no {file} beside the manuscript — add it with: {cmd}': '原稿の隣に {file} がない。足すなら: {cmd}',
    'paper: add appendix.md as well (also to an existing paper)': '論文: appendix.md も置く（既にある論文にも足せる）',
    'paper: add main.tex as well, for LaTeX (also to an existing paper)': '論文: LaTeX 用の main.tex も置く（既にある論文にも足せる）',
    '(unknown)': '(不明)',
    '({n} watched {n|input|inputs})': '（監視中の入力 {n} 件）',
    '--no-citations: leaving citations unresolved (for a draft)': '--no-citations: 引用を解決しない（下書き用）',
    'All clear. Ready to submit': '問題なし。投稿できる',
    'Analysis': '分析',
    'Analysis (only when you use a .qmd)': '分析（.qmd を使うときだけ）',
    'Beamer theme metropolis': 'Beamer テーマ metropolis',
    'Building now would put fake numbers in the text -> octavo analysis run': 'このまま組むと本文に仮の数字が入る -> octavo analysis run',
    'CJK fonts': '日本語フォント',
    'CSL cache': 'CSL キャッシュ',
    'CSL citations (--citeproc built in)': 'CSL 引用（--citeproc 内蔵）',
    'Ctrl-C to stop': 'Ctrl-C で止める',
    'Every common format (typst / docx) works.': '通常使う形式（typst / docx）はすべて出力できる。',
    'Fix it, then octavo build. To build with assets/values/ as it is: octavo build --no-analysis': '直してから octavo build を実行する。いまの assets/values/ のまま変換したいなら octavo build --no-analysis',
    'For LaTeX / Beamer too: {cmd} --with-tex': 'LaTeX / Beamer も使うなら: {cmd} --with-tex',
    "For a newer one, take the .deb from https://github.com/jgm/pandoc/releases (apt's is often old)": '新しい版が要るなら https://github.com/jgm/pandoc/releases から .deb を入れる（apt の版は古いことが多い）',
    'Formats you can produce': '出力できる形式',
    'Harano Aji fonts (for LaTeX)': '原ノ味フォント（LaTeX 用）',
    'If it is a result:  add ov_value("name", value) to the .qmd and write {{name}} in the text': '分析結果なら:  .qmd に ov_value("名前", 値) を足し、本文を {{名前}} にする',
    'If it is not:       add the string to lint_accepted in octavo.config.py': '結果でないなら: octavo.config.py の lint_accepted にその文字列を足す',
    'If you did not, something went wrong — the raw data has been overwritten': '差し替えた覚えがないなら、原データが書き換えられている',
    'If you replaced the data on purpose: octavo analysis run --force, then octavo data hash to record it again': 'データを差し替えたなら octavo analysis run --force のうえ octavo data hash で記録し直す',
    'Japanese document class ltjsarticle': '日本語文書クラス ltjsarticle',
    'Keep this file in git — data/ itself is not, so this is the only record there will be': 'このファイルは git で管理する（data/ 自体は git に入らないので、これが唯一の記録になる）',
    'LuaLaTeX': 'LuaLaTeX',
    'MISSING': '欠落',
    'Next:': '次にやること:',
    'No drift. This is the same data as when it was recorded': '食い違いなし。記録したときと同じデータを使っている',
    'Nothing recorded yet. Make it with: octavo data hash': 'まだ記録がない。octavo data hash で作る',
    'OK': 'OK',
    'Python': 'Python',
    'Quarto': 'Quarto',
    'Recorded fingerprints for {n} {n|file|files} in {path}': '{n} ファイルのハッシュ値を {path} に記録した',
    'Recorded {when}: {n} {n|file|files}': '{when} の記録: {n} ファイル',
    'References cited:': '引用している文献:',
    'To start from scratch: octavo init my-paper': '一から作るなら: octavo init my-paper',
    'TeX (only when you use LaTeX / Beamer)': 'TeX（LaTeX / Beamer を使うときだけ）',
    "The working rules are in CLAUDE.md; the manual is Octavo's guide.": '作業の約束事は CLAUDE.md に、使い方は Octavo の手引きにある。',
    'To install them all: {cmd}': 'まとめて入れるなら: {cmd}',
    'Tools': 'ツール',
    'Typst': 'Typst',
    'Typst 0.14 or newer': 'Typst 0.14 以上',
    'Typst can see no CJK font': 'Typst から見える日本語フォントがない',
    'Typst output (-t typst)': 'Typst 出力（-t typst）',
    'What to add': '足すもの',
    'Wrote a project skeleton in {path}:': '{path} にひな型を作った:',
    'Wrote {path}. Open it in Word, set up the styles (Heading 1, Body Text, Table Caption and so on), then write this in octavo.config.py:': '{path} を作った。Word で開いてスタイル（見出し 1、本文、Table Caption 等）を整え、octavo.config.py に次を書く:',
    'Zotero collection name (leave it out for the whole library)': 'Zotero のコレクション名（省略で全体）',
    'Zotero is not answering': 'Zotero が応答しない',
    'Zotero is not answering ({where}).': 'Zotero が応答しない（{where}）。',
    'Zotero local API / collection {name}': 'Zotero ローカル API / コレクション {name}',
    'Zotero local API / the whole library': 'Zotero ローカル API / ライブラリ全体',
    '\\poscite{{{key}}}: no such key in the .bib': '\\poscite{{{key}}}: .bib にキーがない',
    'a CJK font for Typst': 'Typst 用の日本語フォント',
    "a Typst numbering string ('1.' and the like) or None": "Typst の numbering 文字列（'1.' など）か None",
    'a Word file for your coauthors': '共著者に渡す Word ファイル',
    'a conditional': '条件分岐',
    'a document called {name} already exists ({path})': '同じ名前の文書が既にある: {name}（{path}）',
    "a hex colour like '#0e2f92', or None": "'#0e2f92' のような16進数のカラーコードか None",
    'a style ID or an alias': 'スタイル ID か別名',
    'install TeX to use this (missing: {what})': 'TeX を入れれば出力できる（足りない: {what}）',
    'add a manuscript (as many as you like)': '原稿を足す（何本でも）',
    'add one with octavo new paper|slides|lecture <name>, or check documents in octavo.config.py': 'octavo new paper|slides|lecture <名前> で足すか、octavo.config.py の documents を確かめる',
    'add the blind-review checks as well (self-citations and the like)': '匿名審査で出すときの検査も足す（自己引用など）',
    'added': '追加された値',
    'aliases:': '別名:',
    '{n|the one is|all # are} in the .bib': '{n} 件すべて .bib にある',
    '{n|the one is|all # are} up to date': '{n} 本とも最新',
    '{n|the one is|all # are} up to date (not running {n|it|them})': '{n} 本とも最新（実行しない）',
    '{n|the one resolves|all # resolve}': '{n} 個すべて解決できる',
    'also list entries you never cite': '引いていない書誌も出す',
    'also list values the text does not use': '本文が使っていない値も出す',
    'analysis': '分析',
    'analysis freshness': '分析が最新か',
    "analysis takes either 'analysis.qmd' or {{'src': '…', 'deps': ['data/*.csv'], 'manual': True}} (got {got})": "analysis には 'analysis.qmd' か {{'src': '…', 'deps': ['data/*.csv'], 'manual': True}} の形で書く（いまは {got}）",
    'appendix': '付録',
    'are you reaching for a Windows Zotero from inside WSL? (then either put WSL2 in mirrored networking mode, or export the library from Zotero by hand and put it at bib_file)': 'WSL から Windows の Zotero を見ようとしていないか（その場合は WSL2 のネットワークモードを mirrored にするか、Zotero 側で手動でライブラリを書き出して bib_file に置くこと）',
    'beamer': 'beamer',
    'bib': '書誌',
    'bib contents': '書誌の内容',
    'biber': 'biber',
    'biber (not needed with CSL)': 'biber（CSL 運用では不要）',
    'build a small manuscript for real and show how the citations come out': '小さな原稿を実際に組んで、引用の出方を見せる',
    'build document example-paper as Word': '文書 example-paper を Word にする',
    'build every format, typeset them too': 'すべての形式を作り、組版まで行う',
    'build everything the config says': '設定どおりに全部作る',
    'build for blind review (hide anything identifying)': '匿名審査用に組む（著者が分かる箇所を伏せる）',
    'build the appendix too': '付録も変換する',
    'build the manuscripts': '原稿を変換する',
    'building only session {part} of {file}': '{file} の {part} 回だけを組む',
    'building with anything identifying hidden (::: {.no-anonymous} blocks and the title-block metadata)': '著者が分かる箇所を伏せて組む（::: {.no-anonymous} で囲んだ部分と、タイトル部分のメタデータ）',
    'bundle packs one format at a time (--to typst, say)': 'bundle は1つの形式だけをまとめる（--to typst など）',
    'cannot compare with git: {why}': 'git と比べられない: {why}',
    'cannot list the collections ({why})': 'コレクション一覧を取得できない（{why}）',
    'cannot read {file}: {why}': '{file} を読めない: {why}',
    'cannot read {path} as a .docx ({why})': '.docx として読めない: {path}（{why}）',
    'cannot run git: {why}': 'git を呼べない: {why}',
    'cannot run it: {why}': '実行できない: {why}',
    'check that the words around them ("slightly", "about" and the like) still hold': '本文の言い回し（「わずかに」「約」など）も合っているか確かめること',
    'citation keys': '引用キー',
    'comment': 'コメント',
    'comments only': 'コメントだけ',
    'compared with {when}': '{when} の時点との比較',
    'contents differ': '内容が異なる',
    'could not fetch the CSL style {id}: {why}': 'CSL スタイル {id} を取得できなかった: {why}',
    "could not fetch the CSL, but chicago-author-date is pandoc's built-in default — carrying on": 'CSL を取得できなかったが、chicago-author-date は pandoc の内蔵の既定なのでそのまま進める',
    'could not get the default reference.docx out of pandoc:': 'pandoc の既定 reference.docx を取り出せなかった:',
    'cross-check citation keys against the .bib': '引用キーと .bib の突き合わせ',
    'cross-check {{…}} against assets/values/': '本文の {{…}} と assets/values/ の突き合わせ',
    'cross-check {{…}} in the text against assets/values/': '本文の {{…}} と assets/values/ の突き合わせ',
    'cut it down, or check the journal rules': '削るか、雑誌の規定を確かめる',
    'data': 'データ',
    'data fingerprints': 'データのハッシュ値',
    'data/raw is not included (--with-raw-data adds it, once you have checked it may be shared)': 'data/raw は入れていない（--with-raw-data で入る。再配布の可否を確かめてから）',
    'decimal': '小数',
    'decimal in parentheses (a standard error?)': '括弧内の小数（標準誤差？）',
    'deleted': '削除',
    'diagnose the environment': '環境の診断',
    'did you mean: {key}': 'もしかして: {key}',
    'display language': '表示言語',
    'do not go and fetch a CSL': 'CSL を取りに行かない',
    'do not run the .qmd (build with assets/values/ as it is)': '.qmd を実行しない（いまの assets/values/ のまま変換する）',
    'document names (default: all of them)': '文書の名前（既定: 全部）',
    'documents': '文書',
    'documents in octavo.config.py is not picking up {glob} — check it': 'octavo.config.py の documents が {glob} に一致していない。documents を確認する',
    "documents['{name}'] has a bad profile: {got} (one of {allowed})": "documents['{name}'] の profile が不正: {got}（{allowed}）",
    "documents['{name}'] has bad targets: {bad}": "documents['{name}'] の targets が不正: {bad}",
    "documents['{name}'] needs at least 'src'": "documents['{name}'] には少なくとも 'src' が要る",
    'dropped {n} {n|block that does|blocks that do} not belong in this output': '用途に合わないブロック {n} 個を落とした',
    'dropped {n} needless {n|field|fields} and wrote {path} (the original is untouched)': '{n} 個の余計なフィールドを落として {path} に書いた（元のファイルは触っていない）',
    'e.g.': '例:',
    'environment record': '環境の記録',
    'every figure the text uses is there': '本文が貼っている図は揃っている',
    'every one matches a .qmd': '全部が .qmd に対応している',
    'every {{…}} in the text resolves': '本文の {{…}} はすべて解決できる',
    'failed:': '失敗:',
    'failed: {unit}': '失敗: {unit}',
    'fatal ': '致命的 ',
    "fetch a journal's style (CSL)": '雑誌の書式（CSL）を取得する',
    'fetch it with: octavo csl get {id}': 'octavo csl get {id} で取得できる',
    'fetch the .bib from Zotero': 'Zotero から .bib を取得する',
    'fetched the CSL: {path}': 'CSL を取得した: {path}',
    'figure files': '図のファイル',
    '{path} (and .pdf — placeholders)': '{path}（と .pdf。仮の図）',
    'files under data/ right now: {n}': 'いま data/ にあるファイル: {n} 件',
    'find results typed into the manuscript': '原稿に手入力された数値を探す',
    'fontconfig': 'fontconfig',
    'for blind review (run octavo build --anonymous first)': '匿名審査用（先に octavo build --anonymous）',
    'for blind review, decide whether to mask them as Author (year) — it depends on the journal': '匿名審査なら Author (年) に伏せるか判断する（雑誌の規定による）',
    'format (default: typst)': '形式（既定: typst）',
    'formats (default: everything that works)': '形式（既定: 出力できるもの全部）',
    'found nothing that looks like a hand-typed result': '原稿に手入力された分析結果らしき数値は見つからなかった',
    'fresh': '最新',
    'octavo analysis run, or check the spelling of the name': 'octavo analysis run、または名前の綴りを確かめる',
    'octavo analysis run (or octavo build, for a figure drawn in Typst)': 'octavo analysis run（Typst で描いた図なら octavo build）',
    'octavo build <name> could not tell them apart — pick another': 'octavo build <名前> で区別できなくなるので、別の名前にすること',
    'octavo checkbib (what you decide not to fix goes in bib_accepted)': 'octavo checkbib（直さないと決めたものは bib_accepted へ）',
    'octavo data hash to record / status to check': 'octavo data hash で記録する / status で確かめる',
    'octavo lint (what is not a result goes in lint_accepted)': 'octavo lint（結果でないものは lint_accepted へ）',
    'octavo — build LaTeX / Typst / Beamer / Word from a Markdown manuscript.': 'octavo — Markdown の原稿から LaTeX / Typst / Beamer / Word を作る。',
    'gathered {n} {n|file|files} into {path}': '{n} ファイルを {path} に集めた',
    'git': 'git',
    'gone': '存在しない',
    'hand-typed numbers': '手入力の数値',
    'how it runs': '実行環境',
    'if you deleted or renamed a .qmd, delete its .json too': '.qmd を消した／改名したなら、この .json も消す',
    'if you deleted or renamed the .qmd, delete this too (stale numbers keep reaching the text). If you wrote it by hand, leave it': '.qmd を消した／名前を変えたなら、このファイルも消す（古い数値が本文に入り続ける）。手で置いたものならそのままでよい',
    'in the text but with no value (left as they are):': '本文にあるのに値がない（そのまま残る）:',
    'inserted': '挿入',
    'insertions only': '挿入だけ',
    'install it from https://github.com/typst/typst/releases (cargo works too)': 'https://github.com/typst/typst/releases から入れる（cargo でも可）',
    'is Settings -> Advanced -> "Allow other applications on this computer to communicate with Zotero" on?': '設定 → 詳細 →「他のアプリケーションとの通信を許可」が入っているか',
    'is Zotero running?': 'Zotero を起動しているか',
    'is the analysis (.qmd) up to date?': '分析 (.qmd) が最新かどうか',
    'it needs Zotero 7 or newer, with Settings -> Advanced -> "Allow other applications" turned on': 'Zotero 7 以降で、設定 → 詳細 →「他のアプリケーションとの通信を許可」が要る',
    'just one session': '1回分だけ',
    'keep luatexja / ltjsarticle in main.tex': 'main.tex の luatexja / ltjsarticle を外さないこと',
    'keep what it built': '生成したファイルを残す',
    'kept in: {path}': '置き場所: {path}',
    'kept: {path}': '残した: {path}',
    'latexmk': 'latexmk',
    'leave citations unresolved (a fast look at a draft)': '引用を解決しない（下書きを速く見たいとき）',
    'leave it as a folder instead of a zip': 'zip にせずフォルダで残す',
    'left alone': 'そのまま',
    'length': '分量',
    "list a coauthor's tracked changes": '共著者の変更履歴を一覧にする',
    'list the output formats': '出力できる形式の一覧',
    'list the references you cite': '引いている文献を一覧する',
    'list the registered manuscripts': '登録されている原稿の一覧',
    'ltjsarticle (texlive-lang-japanese)': 'ltjsarticle（texlive-lang-japanese）',
    'luatexja': 'luatexja',
    'machine-readable JSON': 'JSON 形式',
    'made': '作った',
    'made {n} {n|file|files}': '{n} ファイル作った',
    'made {path}': 'できた: {path}',
    'make the post-acceptance replication package (a different set of files)': '採択後の再現用パッケージを作る（投稿用とは中身が異なる）',
    'manuscript': '原稿',
    'matches the record from {when} ({n} {n|file|files})': '{when} の記録と一致（{n} 件）',
    'missing: {what}': '足りない: {what}',
    'name': '名前',
    'next:': '次:',
    '{n} manual {n|one is|ones are} stale. octavo build does not run {n|it|them}: run {n|it|them} with octavo analysis run': '手動指定の {n} 本が古い。octavo build では実行されないので、octavo analysis run で実行する',
    'running {unit}…': '実行中: {unit}…',
    'manual': '手動',
    '{unit} is stale but runs only when asked (manual) — octavo analysis run {unit}': '{unit} は古いが、手動指定なので自動では実行しない — octavo analysis run {unit}',
    'no registered analysis called {name}': '{name} という分析は登録されていない',
    'registered: {names}': '登録されているもの: {names}',
    'with run: only these .qmd (run even if not stale)': 'run と一緒に: この .qmd だけ（古くなくても実行する）',
    'name a .qmd only with run: octavo analysis run {names}': '.qmd を指定できるのは run のときだけ: octavo analysis run {names}',
    'macOS: LuaLaTeX finds the system fonts itself': 'macOS: LuaLaTeX はシステムのフォントを自分で探す',
    'brew install pandoc': 'brew install pandoc',
    'MacTeX brings the Harano Aji fonts LaTeX uses: brew install --cask mactex-no-gui': 'LaTeX が使う原ノ味フォントは MacTeX に入っている: brew install --cask mactex-no-gui',
    'not needed on macOS': 'macOS では要らない',
    'brew install --cask font-biz-udgothic font-biz-udmincho font-inter': 'brew install --cask font-biz-udgothic font-biz-udmincho font-inter',
    'brew upgrade pandoc': 'brew upgrade pandoc',
    'brew install --cask mactex-no-gui (several GB; open a new terminal afterwards)': 'brew install --cask mactex-no-gui（数 GB。入れたらターミナルを開き直す）',
    'comes with MacTeX: brew install --cask mactex-no-gui': 'MacTeX に入っている: brew install --cask mactex-no-gui',
    'brew install typst': 'brew install typst',
    'brew upgrade typst': 'brew upgrade typst',
    'not needed with CSL. Only if you go back to biblatex: it comes with MacTeX': 'CSL なら不要。biblatex に戻すときだけ（MacTeX に入っている）',
    'comes with MacTeX (or set beamer_theme to default if you do not use it)': 'MacTeX に入っている（使わないなら beamer_theme を default に）',
    'brew install --cask font-noto-sans-cjk-jp font-noto-serif-cjk-jp. For a font kept elsewhere, point TYPST_FONT_PATHS at its folder': 'brew install --cask font-noto-sans-cjk-jp font-noto-serif-cjk-jp。別の場所のフォントを使うなら TYPST_FONT_PATHS にそのフォルダを',
    'referenced by {name}': '{name} が参照している',
    'output': '出力',
    'bibliography': '書誌',
    'there is no paper. Name the document to package (octavo bundle <name>)': '論文がない。まとめる文書の名前を指定すること（octavo bundle <名前>）',
    'there is more than one paper. Name the one to package: octavo bundle <name>': '論文が複数ある。どれをまとめるか指定すること: octavo bundle <名前>',
    'papers: {names}': '論文: {names}',
    'unknown output format: {name}': '不明な出力形式: {name}',
    'available: {names}': '使えるもの: {names}',
    'body word count': '本文の語数',
    'body character count': '本文の文字数',
    'abstract word count': '要旨の語数',
    'abstract character count': '要旨の文字数',
    ' words': '語',
    ' characters': '字',
    '{doc}: {what}': '{doc} の{what}',
    '(appendix)': '(付録)',
    "'ja' or 'en'": "'ja' か 'en'",
    "'csl' or 'native'": "'csl' か 'native'",
    "'16-9' or '4-3'": "'16-9' か '4-3'",
    'needed for CSL citation processing (--citeproc)': 'CSL による引用処理（--citeproc）に要る',
    'This list is **for reading**. Do not copy the docx back into the manuscript.': 'この一覧は**読むためのもの**。docx をそのまま原稿に戻さないこと。',
    'In the returned docx, {{n_obs}} is already the literal text "1,523";': '戻ってきた docx では {{n_obs}} が既に「1,523」という文字になっていて、',
    'writing it back pins the number into the manuscript (and breaks what this tool is for).': '書き戻すと数値の出所が原稿に固定される（このツールの前提が壊れる）。',
    'Make the edits in the .md, and change numbers in the .qmd.': '直すのは .md 側、数値を変えるなら .qmd 側。',
    'no year (shows as [n.d.])': '年がない（[n.d.] と出る）',
    'no author': '著者がない',
    'organization name split into surname and given name': '団体名が姓名に割れている',
    'no page range or DOI': 'ページも DOI もない',
    'no journal title': '掲載誌名がない',
    'no publisher': '出版社がない',
    'key contains characters that break typesetting': 'キーに組版で壊れる文字が入っている',
    'contains Japanese but has no langid': '日本語を含むのに langid がない',
    'set Language to ja in Zotero': 'Zotero の Language を ja に',
    'needed to write {what}': '{what} の書き出しに要る',
    'main.typ must set a CJK font (check it is installed with: typst fonts)': 'main.typ が CJK フォントを設定していること（typst fonts で入っているか確認）',
    'Typst slides': 'Typst スライド',
    'Typst speaker script': 'Typst 台本',
    'Beamer slides': 'Beamer スライド',
    'LaTeX (LuaLaTeX)': 'LaTeX (LuaLaTeX)',
    'Word (.docx)': 'Word (.docx)',
    '({name} lives beside the manuscript)': '（{name} は原稿の隣に置く）',
    'no BibTeX came back (check the Zotero version and settings)': 'BibTeX が返ってこなかった（Zotero の版と設定を確認）',
    'no _session in the value files': '値のファイルに _session がない',
    'no analysis is registered. Write this in octavo.config.py:': '分析は登録されていない。octavo.config.py に次を書く:',
    'no collection called {name}.': 'コレクション {name} がない。',
    'no config file at {path}': '設定ファイルがない: {path}',
    'no documents registered. Add one with e.g. octavo new paper <name>': '文書が登録されていない。octavo new paper <名前> などで足す',
    'no documents to build. Add a manuscript with octavo new paper|slides|lecture <name>, or write it into documents in octavo.config.py': '作る文書がない。octavo new paper|slides|lecture <名前> で原稿を足すか、octavo.config.py の documents に書くこと',
    'no fc-list, so this cannot be checked': 'fc-list がないので確認できない',
    'no locale set': 'ロケール未設定',
    'no manuscript at {path}': '原稿がない: {path}',
    'no marks left': '印は残っていない',
    'no output at {dir} (run octavo build --to {target} first)': '出力がない: {dir}（先に octavo build --to {target}）',
    'no placeholders left': '仮の図は残っていない',
    'no quarto, so {units} cannot be run. The numbers in {dir}/ may be stale (octavo doctor says how to install it)': 'Quarto がないので {units} を実行できない。{dir}/ の数値は古いままかもしれない（入れ方は octavo doctor）',
    "no reference document at {path} — using pandoc's default look": '参照用の docx が見つからない: {path} — pandoc の既定の見た目になる',
    'no sign this was built anonymously. Run octavo build --anonymous --to <format> first': '匿名で組んだ跡がない。先に octavo build --anonymous --to <形式> を実行すること',
    'no such file: {path}': 'ファイルがない: {path}',
    'no tracked changes and no comments': '変更履歴もコメントも見つからなかった',
    'no typst, so this cannot be checked': 'typst がないので確認できない',
    'no {cmd}, so it was skipped': '{cmd} がないので飛ばした',
    'no {pattern} in {dir} (run octavo build {doc} --to {target} first)': '{dir} に {pattern} がない（先に octavo build {doc} --to {target}）',
    'none found': '見つからない',
    'none of the numbers the text prints have changed': '本文に出る数字は変わっていない',
    'not found': '見つからない',
    'not found (only needed if the .qmd is R)': '見つからない（.qmd を R で書くときだけ要る）',
    'not found (only needed to run a .qmd)': '見つからない（.qmd を実行するときだけ要る）',
    'not found (see octavo doctor)': '見つからない（octavo doctor 参照）',
    'not found: {unit}': '見つからない: {unit}',
    'not needed with CSL. Only if you go back to biblatex: sudo apt install biber': 'CSL 運用では要らない。biblatex に戻すときだけ sudo apt install biber',
    'no `::: notes` — this is just the deck on paper': '`::: notes` が1つもない。スライドと同じ中身だけの紙になる',
    'not recorded': '記録にない',
    'note': '注意',
    'nothing fatal ({n} to look at)': '致命的な問題はない（注意 {n} 件）',
    'nothing recorded ({n} {n|file|files} under data/)': '記録がない（data/ に {n} 件）',
    'nothing to compare with. Run octavo analysis run once and the values from just before are kept as the reference': '比べる相手がない。octavo analysis run を1度実行すると、その直前の値が控えとして残る',
    'nothing to connect to': '接続先がない',
    'nothing wrong': '問題なし',
    'check everything before submitting': '投稿前にまとめて検査する',
    'output formats: {list} / all / print. Several, comma-separated': '出力形式: {list} / all / print。コンマ区切りで複数',
    'overwrite files that are already there': '既存のファイルも上書きする',
    'p value': 'p 値',
    'packed {n} {n|file|files} into {path} ({size} bytes)': '{n} ファイルを {path} にまとめた（{size} bytes）',
    'pandoc': 'pandoc',
    'pandoc 2.11+ (CSL citations)': 'pandoc 2.11+（CSL 引用）',
    'pandoc 3.1+ (Typst output)': 'pandoc 3.1+（Typst 出力）',
    'pandoc failed:': 'pandoc が失敗した:',
    'pandoc not found.': 'pandoc が見つからない。',
    'pandoc {need} or newer is required (this is {got})': 'pandoc {need} 以上が要る（いま {got}）',
    "pandoc's built-in chicago-author-date is used (no .csl file)": 'pandoc 内蔵の chicago-author-date を使う（.csl ファイルはなし）',
    "pandoc's default (chicago-author-date)": 'pandoc 既定 (chicago-author-date)',
    'paragraph {n}': '段落 {n}',
    'percentage': 'パーセント',
    'placeholder values': '仮の値',
    'print every detail': '内訳を全部出す',
    'print one line of machine-readable JSON (for the VS Code extension and friends)': 'JSON 形式で1行出す（VS Code 拡張などが読み取る）',
    'print the results as machine-readable JSON (including where the PDF landed)': '結果を JSON 形式で出す（できた PDF の場所を含む）',
    'profiles:': 'プロファイル:',
    'put data/raw in the --replication package too (check it may be shared)': '--replication に data/raw も入れる（再配布可か確かめて）',
    'ran {unit} ({secs}s)': '実行した: {unit}（{secs} 秒）',
    'raw data': '原データ',
    "read a coauthor's tracked changes out of a .docx": '共著者が返してきた .docx の変更履歴を見る',
    'rebuild whenever a manuscript is saved': '原稿を保存するたびに作り直す',
    'record / check the data fingerprints': 'データのハッシュ値を記録する／確かめる',
    'recorded but gone': '記録にあるがない',
    'rename one of the manuscripts (or its folder)': 'どちらかの原稿（か、そのフォルダ）の名前を変えること',
    'repackage it for a submission system': '投稿システムに上げる形にまとめ直す',
    'repackage it for submission': '投稿用にまとめ直す',
    'replace them with your own content, comment mark and all': '自分の内容に置き換えて、印のコメントごと消す',
    'results go in: {path}': '結果の置き場: {path}',
    'values_dir is outside the repository, so it cannot be compared with git': 'values_dir がリポジトリの外にあるので git と比べられない',
    'run it again even if it is not stale': '古くなくても再実行する',
    'run the .qmd again even if it is not stale': '古くなくても .qmd を再実行する',
    'run the analysis (.qmd)': '分析（.qmd）を実行する',
    'run the analysis with octavo analysis run — as it is, the numbers that get typeset are fake': 'octavo analysis run で分析を実行する（いまのままでは仮の数字が組まれる）',
    'run the analysis with octavo analysis run, and check the spelling of the names': 'octavo analysis run で分析を実行する。名前の綴りも確かめる',
    'run the stale .qmd through quarto': '古い .qmd を Quarto で実行する',
    'running the analysis once records it (for the replication package)': '分析を1度実行すると記録される（再現用パッケージ用）',
    'sample size': '標本サイズ',
    'see whether the tools are there': '環境が足りているか見る',
    'self-citations': '自己引用',
    'show the heading structure': '原稿の見出し構成を見る',
    'skipped: needs pandoc {ver} or newer': '飛ばす: pandoc {ver} 以上が要る',
    'something changed, rebuilding': '変わったので作り直す',
    'something is missing, clashing, or not anonymised. Fix what is above before submitting': '欠落・衝突・匿名化の漏れがある。上を見て直してから投稿する',
    'stale': '古い',
    'status=check against the record (default) / hash=write the record': 'status=記録と食い違わないか（既定） / hash=記録する',
    'status=see whether it is up to date (default) / run=run it': 'status=最新かどうか見る（既定） / run=実行する',
    'stopped': '止めた',
    'style IDs are listed at https://www.zotero.org/styles': 'スタイル ID は https://www.zotero.org/styles で確認できる',
    'substituted {n}': '{n} 個を差し込んだ',
    'sudo apt install fontconfig': 'sudo apt install fontconfig',
    'sudo apt install fonts-noto-cjk (then fc-cache -f). For a font kept elsewhere, point TYPST_FONT_PATHS at its folder': 'sudo apt install fonts-noto-cjk（入れた後 fc-cache -f）。別の場所のフォントなら TYPST_FONT_PATHS でそのフォルダを指す',
    'sudo apt install fonts-noto-cjk fonts-noto-cjk-extra': 'sudo apt install fonts-noto-cjk fonts-noto-cjk-extra',
    'sudo apt install latexmk': 'sudo apt install latexmk',
    'sudo apt install pandoc (if it is old, take the .deb from GitHub)': 'sudo apt install pandoc（古ければ GitHub の .deb を入れる）',
    'sudo apt install texlive-lang-japanese': 'sudo apt install texlive-lang-japanese',
    'sudo apt install texlive-latex-extra (or set beamer_theme to default if you do not use it)': 'sudo apt install texlive-latex-extra（使わないなら beamer_theme を default に）',
    'sudo apt install texlive-latex-recommended': 'sudo apt install texlive-latex-recommended',
    'sudo apt install texlive-luatex texlive-lang-japanese': 'sudo apt install texlive-luatex texlive-lang-japanese',
    'table files': '表のファイル',
    'take a newer .deb from https://github.com/jgm/pandoc/releases': 'https://github.com/jgm/pandoc/releases から新しい .deb を入れる',
    'talk to Zotero': 'Zotero との受け渡し',
    'template leftovers': 'ひな型の残り',
    'that name will not do: {name} (no spaces, no / or \\, and it cannot start with a dot)': 'この名前は使えない: {name}（空白・/・\\ を含まず、. で始まらない名前にする）',
    'the .docx that came back': '戻ってきた .docx',
    'the A4 handout, through to PDF': 'A4 プリントを PDF まで',
    'the CJK font in typst_slides_font must be installed (check with: typst fonts)': 'typst_slides_font の日本語フォントが入っていること（typst fonts で確認）',
    'the CSL style {id} is not in the local cache.': 'CSL スタイル {id} がローカルにない。',
    'the Zotero local API is unavailable ({why}).': 'Zotero のローカル API が使えない（{why}）。',
    'the analysis failed. Building around stale numbers would contradict the text, so this stops here.': '分析が失敗した。数値が古いまま変換すると本文と食い違うので止める。',
    'the analysis has never run: {files} {n|is|are} the starter values octavo wrote': '分析を1度も実行していない: {files} は octavo が置いた仮の値',
    'the bibliography is unreadable or empty: {path}': '書誌が読めない、または空: {path}',
    'the cache is empty. Fetch one with e.g. octavo csl get apa': 'キャッシュは空。octavo csl get apa などで取得できる',
    'the document name (it becomes the file or folder name)': '文書の名前（ファイル名・フォルダ名になる）',
    "the journal's style (CSL)": '雑誌の書式（CSL スタイル）',
    'the slides, one PDF per session': 'スライドを回ごとに PDF まで',
    'the slides, through to PDF': 'スライドを PDF まで',
    'the style to try': '試す書式',
    'then edit draft and bib_file in it.': 'として作り、draft や bib_file を書き換えること。',
    'available: {names}': 'ある: {names}',
    'there was no data/HASHES.json, so it was written': 'data/HASHES.json がなかったので作った',
    'these are real values': '本物の値が入っている',
    'no values yet (the analysis writes them)': 'まだ値がない（分析が書く）',
    'this is the main.* arrangement, so --compile does not typeset it ({next})': 'main.* 方式なので --compile では組まない（{next}）',
    'main.tex does not define the CSLReferences environment the bibliography uses — octavo template copy paper/csl-preamble.tex has the definition': 'main.tex に、書誌が使う CSLReferences 環境の定義がない — 定義は octavo template copy paper/csl-preamble.tex にある',
    'to mark a version, tag it: git tag v1-submitted': '版に目印を付けるには git tag を使う: git tag v1-submitted',
    'to place it by hand: {path}': '手で置く場合: {path}',
    'total (without duplicates): {n}': '合計（重複を除く）: {n} 件',
    'treat warnings as failures too (for CI)': '注意も失敗として扱う（CI 向け）',
    'two documents share the name {name}': '文書の名前がぶつかっている: {name}',
    'two files share the name {name} ({a} and {b}) — rename one': '同じ名前のファイルが2つある: {name}（{a} と {b}）— 片方を改名すること',
    'typeset it as well (latexmk / typst compile)': '組版まで実行する（latexmk / typst compile）',
    'typeset main.typ through to PDF': 'main.typ を組んで PDF まで',
    'typst': 'typst',
    'unknown formats in figure_ext: {names}': 'figure_ext に不明な形式: {names}',
    'unknown formats in out_dirs: {names}': 'out_dirs に不明な形式: {names}',
    'unknown kind: {kind} (one of {allowed})': '不明な種類: {kind}（{allowed}）',
    'unresolved {ref} — not reachable from the output ({dir}/)': '{ref} が見つからない — 出力（{dir}/）から辿れない',
    'upgrade Typst (octavo setup installs the version this was tested on)': 'Typst を更新する（octavo setup が、動作確認済みの版を入れる）',
    'upgrade to pandoc 2.11 or newer (CSL citations need it)': 'pandoc 2.11 以上に更新する（CSL 引用に必要）',
    'upgrade to pandoc 3.1 or newer': 'pandoc 3.1 以上に更新する',
    'using the styles from {file}': '{file} のスタイルを使う',
    'value files': '値のファイル',
    'value files with no matching .qmd:': '対応する .qmd がない値のファイル:',
    'values nothing uses:': '使っていない値:',
    'warning: unknown keys in the config (ignored): {keys}': '警告: 設定に不明なキーがある（無視する）: {keys}',
    'watch the manuscripts and rebuild': '原稿の変更を監視して作り直す',
    'watching: {files}': '監視中: {files}',
    'what came back is not a CSL (check the ID)': '取得したものが CSL ではない（ID の綴りを確認）',
    'what changed since the analysis last ran; pass a git tag or commit to compare with that version': '前に分析を実行したときからの変化。git のタグやコミットを渡すとその版と比べる',
    'what moved since last time (or a git version)': '前回（か git の版）からの数値の変化',
    'where octavo.config.py is (default: here)': 'octavo.config.py の場所（既定: カレント）',
    'where to write it (default: bib_file from the config)': '出力先（既定: config の bib_file）',
    'where to write it (default: submission-<name>.zip)': '出力先（既定: submission-<名前>.zip）',
    'which paper to pack (you can leave this out if there is only one)': 'まとめる論文の名前（論文が1本だけなら省略できる）',
    'within the limits': '規定の範囲に収まっている',
    "without Word's Track Changes on, edits leave no trace": 'Word の「変更履歴の記録」が入っていないと、直した跡は残らない',
    'words (without/with tables): {excl} / {incl}   characters (without spaces): {chars}': '語数（表除く/含む）: {excl} / {incl}\u3000文字数（空白等除く）: {chars}',
    'working in: {path}': '作業場所: {path}',
    "write  'csl': '{id}',  in octavo.config.py": "octavo.config.py に  'csl': '{id}',  と書く",
    'write a Word reference .docx': 'Word のスタイル定義用 .docx を作る',
    'write a project skeleton': 'プロジェクトのひな型を作る',
    'write a project skeleton (add manuscripts with octavo new)': 'プロジェクトのひな型を作る（原稿は octavo new で足す）',
    'wrote {n} {n|entry|entries} to {path} (from {source})': '{n} 件を {path} に書いた（{source}）',
    '{files} {n|is|are} still the starter values octavo wrote.': '{files} は octavo が置いた仮の値のまま。',
    '{file} has no `#` headings, so the slides cannot be split by session': '{file} に `#` 見出しがないのでスライドを回ごとに分けられない',
    '{file} has no session {part} (the `#` heading is gone, or its {{#id}} changed)': '{file} に「{part}」の回がない（`#` 見出しが消えたか、{{#id}} が変わった）',
    '{file} is not a dictionary (ignored)': '{file} の中身が辞書でない（無視する）',
    '{file} is still the starter values octavo wrote. The numbers in the text are fake (octavo analysis run makes them real)': '{file} は octavo が置いた仮の値のまま。本文の数字は仮のもの（octavo analysis run で本物にする）',
    '{file} switches on {guard}, so it does not reach the typeset output. But **{needle} is still in the source file** — delete it if the journal wants the .tex itself': '{file} は {guard} で切り替えているので組版には出ない。ただし**原稿ファイルの中には「{needle}」が残る** — .tex ごと出す雑誌なら消すこと',
    '{id} is a dependent style -> fetching its parent {parent}': '{id} は従属スタイル -> 親の {parent} を取得する',
    '{key} must be a list (got {got})': '{key} はリストで書く（いま {got}）',
    '{key} must be {allowed} (got {got})': '{key} は {allowed}（いま {got}）',
    '{label} {n}:': '{label} {n} 件:',
    '{label}: {got}{unit} (limit {limit}{unit}, over by {excess}{unit})': '{label}: {got}{unit}（上限 {limit}{unit}、超過 {excess}{unit}）',
    '{lines} {lines|line|lines} of text / {files} table {files|file|files} — {hint}': '本文 {lines} 行 / 表 {files} ファイル — {hint}',
    '{name} is in both {first} and {second} ({second} wins)': '{name} が {first} と {second} の両方にある（{second} を採る）',
    '{name} is not in {dir}/ (left as it is)': '{name} が {dir}/ にない（そのまま残した）',
    '{needle} is still in {file} (guard it with {guard}, or delete it by hand)': '{file} に「{needle}」が残っている（{guard} で囲むか、手で消すこと）',
    '{n} {n|is|are} in the .bib but never cited ({n|it does|they do} not reach the output)': '.bib にあって引いていないもの {n} 件（残っていても組版には出ない）',
    '{n} {n|is|are} over the limit': '{n} 件が規定を超えている',
    '{n} {n|is|are} stale. Run {n|it|them} with octavo analysis run (octavo build runs {n|it|them} too)': '{n} 本が古い。octavo analysis run で実行する（octavo build でも自動で実行される）',
    '{n} {n|is still a placeholder|are still the placeholders} octavo wrote': '{n} 件が、octavo が置いた仮の図のまま',
    '{n} cached': '{n} 件キャッシュ済み',
    '{n} {n|candidate|candidates}': '候補 {n} 件',
    '{n} {n|change|changes} in {paras} {paras|paragraph|paragraphs}': '{n} 件（{paras} 段落）',
    '{n} {n|citation|citations}': '引用 {n} 件',
    '{n} {n|differs|differ} from the record': '記録と違う {n} 件',
    '{n} {n|difference|differences}:': '食い違い {n} 件:',
    '{n} {n|entry|entries}': '{n} 件',
    '{n} failed': '失敗 {n} 件',
    '{n} {n|family|families}': '{n} 系統',
    '{n} fatal. Typesetting this would be wrong': '致命的 {n} 件。このままでは組んでも間違う',
    '{n} found': '{n} 件',
    '{n} {n|frame|frames}': 'frame {n} 枚',
    '{n} {n|frame looks|frames look} likely to overflow (over {limit} lines) — split {n|it|them}, or use a smaller font': '内容が多くて収まりきらなそうな frame が {n} 枚（{limit} 行超）— 分割するか、小さめのフォントにする',
    '{n} octavo:example {n|mark|marks}': 'octavo:example の印が {n} 箇所',
    '{n} {n|key is|keys are} not in the .bib': '.bib にないキー {n} 件',
    '{n} {n|key is|keys are} not in the .bib — {n|it typesets|they typeset} as ??': '.bib にないキー {n} 件 — 組版で ?? になる',
    '{n} {n|looks like a hand-typed number|look like hand-typed numbers} (if {n|it is a result, move it|they are results, move them} to ov_value() in the .qmd)': '手入力された数値らしきもの {n} 件（分析結果なら .qmd の ov_value() に移す）',
    '{n} missing': '不足 {n} 件',
    '{n} missing — typesetting will fail as it is': '{n} 件足りない — このまま組版すると失敗する',
    '{n} {n|pair looks|pairs look} like the same reference twice': '同じ文献が二重に入っていそう {n} 組',
    '{n} {n|place is|places are} still the template (replace {n|it|them} with your own content and delete the octavo:example {n|mark|marks})': 'ひな型のままの箇所 {n} 件（自分の内容に置き換えて octavo:example の印ごと消す）',
    '{n} possible {n|self-citation|self-citations}: {keys} (whether to mask {n|it|them} depends on the journal)': '自己引用の候補 {n} 件: {keys}（伏せるかどうかは雑誌の規定で判断すること）',
    '{n} {n|reference points|references point} nowhere — typesetting will fail as it is': '指し先を解決できない参照 {n} 件 — このまま組版すると落ちる',
    '{n} {n|slide|slides} (title and section slides not counted)': '{n} 枚（タイトルスライドと節の区切りを除く）',
    '{n} to deal with': '要対応 {n} 件',
    '{n} to look at': '要注意 {n} 件',
    '{n} unresolved': '未解決 {n} 件',
    '{n} {n|value|values} changed:': '変わった値 {n} 件:',
    '{n} {n|value|values} in {path} ({files} {files|file|files})': '{path} の値 {n} 個（{files} ファイル）',
    '{n} with no matching .qmd': '対応する .qmd がないもの {n} 件',
    '{n} — fix {n|it|them} in Zotero and export again': '{n} 件 — Zotero 側で直してエクスポートし直す',
    '{n} — listed in bib_accepted as not worth fixing': '{n} 件 — bib_accepted で直さないと決めたもの',
    '{path} has no CONFIG dictionary': '{path} に CONFIG 辞書がない',
    '{slides} {slides|slide|slides} / {notes} {notes|note|notes}': 'スライド {slides} 枚 / ノート {notes} 個',
    '{stale} of {n} {stale|is|are} stale': '{n} 本中 {stale} 本が古い',
    '{values} {values|value|values} in {files} {files|file|files}': '値 {values} 個 / ファイル {files} 個',
    '{who}: {n}': '{who}: {n} 件',
    '{{…}} in the text': '本文の {{…}}',
    '— fetch one with e.g. octavo csl get apa': '— octavo csl get apa などで取得できる',
    '— set OCTAVO_LANG=ja for Japanese': '— 日本語にするなら OCTAVO_LANG=ja',
    '… and {n} more': '… 他 {n} 件',
    '…and {n} more (--verbose for all of them)': '…ほか {n} 件（--verbose で全部）',
    'installed': '入っている',
    'not installed': '入っていない',
    '      └ renv': '      └ renv',
    '      └ packages': '      └ パッケージ',
    'all load': 'すべて読み込める',
    '{n} {n|package|packages} built for an older R ({versions}) {n|does|do} not load': '古い R（{versions}）向けのパッケージ {n} 個が読み込めない',
    'To rebuild the R packages built for an older R (projects with renv are not affected):': '古い R 向けの R パッケージを入れ直す（renv を使うプロジェクトには影響しない）:',
    ' none ': ' 不足 ',
    'all there: {names}': '揃っている: {names}',
    'missing: {names} (a fallback font is used instead)': 'ない: {names}（代わりのフォントで組む）',
    '  └ default typefaces': '  └ 既定の書体',
    'For the default typefaces:': '既定の書体を入れるなら:',
    'sudo apt install fonts-morisawa-bizud-gothic fonts-morisawa-bizud-mincho fonts-inter (then fc-cache -f)': 'sudo apt install fonts-morisawa-bizud-gothic fonts-morisawa-bizud-mincho fonts-inter（入れた後 fc-cache -f）',
    'show or change the common settings': 'よく使う設定を見る・変える',
    'usage: octavo config set KEY VALUE / octavo config unset KEY': '使い方: octavo config set キー 値 / octavo config unset キー',
    '{key} = {value}  ({path})': '{key} = {value}  （{path}）',
    '(default)': '（既定）',
    'Language of the documents': '文書の言語',
    'Citation style (CSL)': '引用の書式（CSL）',
    'Aspect ratio': '縦横比',
    'Accent colour': 'アクセントカラー',
    'Section name in the top-left corner': '左上の節名',
    'Divider slide for each section': '節ごとの区切りスライド',
    'Heading numbers': '見出しの番号',
    'Word limit (text)': '語数の上限（本文）',
    'Character limit (text)': '文字数の上限（本文）',
    'Word limit (abstract)': '語数の上限（要旨）',
    'Character limit (abstract)': '文字数の上限（要旨）',
    'Documents': '文書',
    'Slides': 'スライド',
    'Submission limits': '投稿規定',
    '{key} cannot be changed from here — edit octavo.config.py': '{key} はここからは変えられない。octavo.config.py を直すこと',
    '{key} cannot be empty': '{key} は空にできない',
    '{key} takes true or false': '{key} は true か false',
    '{key} takes a whole number': '{key} は正の整数',
    '{key} takes one of {allowed}': '{key} は {allowed} のどれか',
    '{key} spans several lines in octavo.config.py — edit it by hand': '{key} は octavo.config.py で複数行にまたがっている。手で直すこと',
    'could not find the end of CONFIG in octavo.config.py': 'octavo.config.py の CONFIG の終わりが見つからない',
    'the result is not a valid config': '書き換えると設定として読めなくなる',

    # ---- octavo template -------------------------------------------------
    'list, copy or compare the templates you can override': '上書きできるテンプレートの一覧・コピー・同梱版との差分',
    'the template, e.g. slides/typst-slides.typ': 'テンプレートの名前（例: slides/typst-slides.typ）',
    'copy it for all your projects (~/.config/octavo/templates)': '自分の全プロジェクト用にコピーする（~/.config/octavo/templates）',
    'which templates are in use, and how to make your own': 'どのテンプレートが使われているか・自分用の作り方',
    'not a template name: {name}': 'テンプレートの名前として読めない: {name}',
    'this project': 'このプロジェクト',
    'yours': '自分用',
    'Looked for in this order (the first one found is used):': 'この順に探し、最初に見つかったものを使う:',
    'Start your own with octavo template copy <name> [--user].': '自分用は octavo template copy <名前> [--user] で作り始める。',
    'which template? (octavo template list shows them)': 'どのテンプレートか（octavo template list で一覧が出る）',
    'no bundled template called {name} (octavo template list shows them)': '{name} という同梱のテンプレートはない（octavo template list で一覧が出る）',
    'not inside a project (no octavo.config.py here) — add --user to copy it for all your projects': 'プロジェクトの中ではない（octavo.config.py がない）— 全プロジェクト用にコピーするなら --user を付ける',
    '{path} is already there (--force overwrites it)': '{path} はもうある（--force で上書き）',
    'wrote {path} — edit it; it is used instead of the bundled one': '{path} にコピーした。これを直せば、同梱のものの代わりにこちらが使われる',
    '{name} is not overridden — the bundled one is in use': '{name} は上書きされていない（同梱のものを使っている）',
    '{path} is the same as the bundled one': '{path} は同梱のものと同じ',
    'keep luatexja-preset in the Beamer header (templates/slides/beamer-header-ja.tex)': 'Beamer のヘッダーに luatexja-preset を残すこと（templates/slides/beamer-header-ja.tex）',

    # ---- octavo release --------------------------------------------------
    'tag this version and put its PDF on a GitHub Release': 'この版にタグを打ち、PDF を GitHub Release に置く',
    'tag this version, PDF to a GitHub Release': 'この版にタグ、PDF を GitHub Release へ',
    'the document name': '文書の名前',
    'what this version is, e.g. v1-submitted (the tag becomes <document>-<label>)': '何の版か。例: v1-submitted（タグは <文書>-<ラベル> になる）',
    "formats (default: the document's targets)": '形式（既定は文書の targets）',
    'check and build, but tag, push and upload nothing': '確認と組版だけして、タグ・push・アップロードはしない',
    'git is not installed': 'git が入っていない',
    'this project is not a git repository (git init, then commit)': 'このプロジェクトは git のリポジトリではない（git init してコミットする）',
    'no document called {name}': '{name} という文書はない',
    'documents: {names}': 'ある文書: {names}',
    '(none)': '（なし）',
    'to add a manuscript: octavo new paper|slides|lecture <name>': '原稿を足すなら: octavo new paper|slides|lecture <名前>',
    '{tag} cannot be a git tag name': '{tag} は git のタグ名にできない',
    'the tag {tag} already exists': 'タグ {tag} はもうある',
    'there are uncommitted changes — commit them first, so the tag points at what gets typeset:': 'コミットしていない変更がある。先にコミットする（タグが組版したものを指すように）:',
    'the analysis values are still the placeholders octavo wrote — run the analysis first': '分析の値が、octavo が置いた仮の値のまま。先に分析を実行する',
    'the analysis is stale ({files}) — run octavo analysis run, commit assets/values/, then release': '分析が古い（{files}）。octavo analysis run のあと assets/values/ をコミットしてから出す',
    'there is no remote called origin to push the tag to': 'タグを push する先（origin）がない',
    'the GitHub CLI (gh) is not installed: https://cli.github.com/ (then gh auth login)': 'GitHub CLI（gh）が入っていない: https://cli.github.com/（入れたら gh auth login）',
    'gh is not logged in (gh auth login)': 'gh にログインしていない（gh auth login）',
    'not released:': '出さなかった:',
    'not released: the build failed': '出さなかった: 組版に失敗した',
    'not released: nothing was typeset to attach (no PDF or Word file)': '出さなかった: 添付するもの（PDF か Word）が組み上がっていない',
    'tag {tag} on {sha}, with:': 'タグ {tag}（{sha}）に添付するもの:',
    '(dry run — nothing tagged, pushed or uploaded)': '（試しに組んだだけ。タグ・push・アップロードはしていない）',
    'the tag was created locally but not pushed: git push origin {tag}': 'タグは手元に打ったが push できなかった: git push origin {tag}',
    'the tag {tag} is pushed, but the release was not made. Run octavo release again after deleting the tag (git tag -d {tag} && git push origin :refs/tags/{tag}), or attach the files by hand with gh release create': 'タグ {tag} は push したが、Release は作れなかった。タグを消してから octavo release をやり直す（git tag -d {tag} && git push origin :refs/tags/{tag}）か、gh release create で手で添付する',

    # ---- octavo selftest の判定 -------------------------------------------
    'frames are created': 'frame ができている',
    'the layout template is included': '体裁のテンプレートが入っている',
    'the analysis values are filled in': '分析の数値が差し込まれている',
    'the figure is in, with its label': '図がラベルつきで入っている',
    'the figure, table and equation carry their labels': '図・表・式にラベルが付いている',
    'the labelled equation is numbered': 'ラベルのある式に番号が付く',
    'numbers are written in (Word does not number)': '番号が文字で入っている（Word は番号を振らない）',
    'citations are resolved by CSL': '引用が CSL で解決されている',
    'citations are resolved': '引用が解決されている',
    'the Japanese text is there': '日本語が入っている',
    'the bibliography is there': '参考文献リストが出ている',
    'the speaker notes are kept': '発表者ノートが残っている',
    'the speaker notes are dropped': '発表者ノートが落ちている',
    'cross-references are #ref(<label>)': '相互参照が #ref(<label>) になっている',
    'cross-references are \\ref': '相互参照が \\ref になっている',
    'citation in the text': '地の文の引用',
    'Japanese citation': '日本語の引用',
    'organization as author': '団体著者',
    '(cannot read it: {error})': '(読めない: {error})',
    # ツールを入れる（octavo setup）・プロジェクトの環境（octavo env）
    '  └ uv (Python)': '  └ uv（Python）',
    'not found (sets up .venv for a Python .qmd)': 'ない（Python の .qmd に使う .venv を作る）',
    'For the analysis ({what}): {cmd}': '分析に使うもの（{what}）: {cmd}',
    'install the tools (pandoc, Typst, quarto, R, uv, fonts)': 'ツールを入れる（pandoc・Typst・Quarto・R・uv・フォント）',
    "set up this project's .venv and renv": 'このプロジェクトの .venv と renv を用意する',
    'TeX Live too (several GB)': 'TeX Live も入れる（数 GB）',
    'leave out quarto': 'Quarto を入れない',
    'leave out R': 'R を入れない',
    'only show what would be installed': '何を入れるか見るだけ',
    'setup.sh or bash is missing, so this cannot run here': 'setup.sh か bash がないので、ここでは動かせない',
    '.venv is already there': '.venv はもうある',
    'requirements.txt lists nothing yet: add a package there, then run this again': 'requirements.txt にはまだ何も書いていない。パッケージを書いたら、もう一度これを実行する',
    'uv is not installed, so this was skipped. octavo setup installs it': 'uv がないので飛ばした。octavo setup が入れる',
    'R is not installed, so this was skipped. octavo setup installs it': 'R がないので飛ばした。octavo setup が入れる',
    'Something failed (see above). Fix it and run octavo env again.': 'うまくいかなかったものがある（上を見る）。直してから octavo env をもう一度',
    'Neither uv nor R is installed. Run octavo setup first.': 'uv も R もない。先に octavo setup を',
    'Windows: LuaLaTeX finds the system fonts itself': 'Windows: LuaLaTeX はシステムのフォントを自分で探す',
    'On Windows, octavo setup does not install TeX. Install MiKTeX or TeX Live yourself if you need LaTeX / Beamer.': 'Windows では octavo setup は TeX を入れない。LaTeX / Beamer が要るなら MiKTeX か TeX Live を自分で入れる',
    'setup.ps1 is missing, so this cannot run here': 'setup.ps1 がないので、ここでは動かせない',
    'the analysis environment (.venv and renv)': '分析の環境（.venv と renv）',
    'The analysis environment is ready. Commit requirements.txt and renv.lock.': '分析の環境ができた。requirements.txt と renv.lock を commit する',
    # 相互参照（crossref.py）
    'write the label on the figure, table, equation or heading: {example}': '図・表・式・見出しにラベルを付ける: {example}',
    'cross-references': '相互参照',
    '{n} {n|label is|labels are} used twice': '{n} 個のラベルが2回使われている',
    'no such {n|label|labels}: {names} (written as ??)': '存在しないラベル: {names}（?? と書いた）',
    '{n} {n|reference points|references point} at no label': '{n} か所の参照の先にラベルがない',
    'octavo analysis run (ov_figure() / ov_table() in the .qmd rewrite them)': 'octavo analysis run（.qmd の ov_figure() / ov_table() が書き直す）',
    'every labelled figure, table and equation is referred to': 'ラベルを付けた図・表・式はどれも参照されている',
    '{n} {n|figure, table or equation is|figures, tables or equations are} never referred to': '{n} 個の図・表・式がどこからも参照されていない',
    'placeholder figures and tables': '仮の図・表',
    'unused labels': '使われていないラベル',
    'refer to it with @label, or drop the label': '@ラベル で参照するか、ラベルを外す',
    'the label {label} is used twice': 'ラベル {label} が2回使われている',
    'every @fig- / @tbl- / @eq- / @sec- has its label': '@fig- / @tbl- / @eq- / @sec- の参照先はすべてある',
    'typeset the example (fake data — for looking only)': '見本を組む（仮のデータ。眺めるためのもの）',
    'what to start with, comma-separated: analysis, paper, slides, lecture (name one as paper=NAME)': '最初に置くもの（カンマ区切り）: analysis, paper, slides, lecture（名前は paper=名前 のように）',
    'make them examples (alone: an analysis of made-up data and an example paper)': '見本にする（これだけなら、仮のデータの分析と見本の論文1本）',
    '(example entries)': '（見本の書誌）',
    'see the values it wrote': '書いた値を見る',
    'typeset it through to PDF': 'PDF まで組む',
    'add a manuscript, an analysis, a figure or a table': '原稿・分析・図・表を足す',
    'paper=a paper / slides=talk slides / lecture=lecture notes (an A4 handout + a deck per session) / analysis=a .qmd / figure=a figure drawn in Typst (figures/<name>.typ) / table=a table made by hand (tables/<name>.csv)': 'paper=論文 / slides=発表スライド / lecture=講義ノート（A4 プリント + 回ごとのスライド） / analysis=分析（.qmd） / figure=Typst で描く図（figures/<名前>.typ） / table=手で作る表（tables/<名前>.csv）',
    'add an analysis (.qmd)': '分析（.qmd）を足す',
    '({section} section)': '（{section} の節）',
    'start with all four: an analysis, a paper, slides and lecture notes': '4つとも置く（分析・論文・スライド・講義ノート）',
    'run it': '実行する',
    'unknown part: {part} (one of {allowed})': '不明な部品: {part}（{allowed} のどれか）',
    'write an example rather than the bare frame': '骨組みではなく見本を置く',
    'appended': '書き足した',
    'no analysis yet. Add one with: {cmd}': 'まだ分析がない。足すなら: {cmd}',
    'There is no analysis in this project, so there is nothing to set up. Add one with: {cmd}': 'このプロジェクトには分析がないので、用意するものはない。足すなら: {cmd}',
    '{key} spans several lines in the manuscript — edit it by hand': '{key} は原稿の中で複数行にまたがっている。手で直す',
    'from the manuscript: {settings}': '原稿の冒頭から: {settings}',
    '{key} cannot be set per document for this kind of manuscript': '{key} はこの種類の原稿では文書ごとに変えられない',
    "this document's own settings (written at the top of its manuscript)": 'その文書だけの設定（原稿の冒頭に書く）',
    '[settings]': '[設定]',
    '{key} takes one or more of {allowed}': '{key} には {allowed} から1つ以上を書く',
    '{file}: targets has unknown formats: {bad}': '{file}: targets に不明な形式がある: {bad}',
    '{file}: {key} must be true or false (got {got})': '{file}: {key} は true か false（いまは {got}）',
    'Output formats': '出力形式',
    '{key} is set per document — use --doc NAME': '{key} は文書ごとに変える。--doc 名前 を付ける',
    '{file}: {key} must be a whole number (got {got})': '{file}: {key} は整数（いまは {got}）',
    'Typst is not installed, so {n|this figure was|these # figures were} not drawn: {files}': 'Typst が入っていないので、図を組まなかった: {files}',
    'could not draw {file}': '{file} を組めなかった',
    'drew {file} -> .pdf, .png': '{file} を組んだ -> .pdf, .png',
    'Figures drawn in Typst': 'Typst で描いた図',
    'a figure could not be drawn, so this stops here (the PDF would show the old one). Fix the .typ above, then build again.': '図を組めなかったので、ここで止める（このまま組むと古い図が載る）。上の .typ を直してから、もう一度 build する。',
    '{path} is already there (a figure from the analysis?) — drawing {name}.typ would overwrite it. Pick another name': '{path} がもうある（分析が書いた図？）。{name}.typ を組むと上書きしてしまうので、別の名前にする',
    'draws it into {files}': '{files} に組まれる',
    'these figures have not been drawn since their .typ changed ({files}) — run octavo build, commit assets/figures/, then release': '.typ を直したあと組まれていない図がある（{files}）。octavo build を実行し、assets/figures/ をコミットしてからリリースする',
    'these tables have not been made since their .csv changed ({files}) — run octavo build, commit assets/tables/, then release': '.csv を直したあと作られていない表がある（{files}）。octavo build を実行し、assets/tables/ をコミットしてからリリースする',
    '{path} is missing (octavo analysis run, or write {csv} and octavo build)': '{path} がない（octavo analysis run か、{csv} を書いて octavo build）',
    'every table the text uses is there': '本文が使う表はすべてある',
    'octavo analysis run (or octavo build, for a table made by hand)': 'octavo analysis run（手で作る表は octavo build）',
    'tables made by hand': '手で作った表',
    'Tables made by hand': '手で作った表',
    '{n} also made by the analysis': '{n} 個は分析も同じ名前で作っている',
    '{n} not made since {n|its .csv|their .csv} changed': '.csv を直したあと作られていないものが {n} 個',
    'rename the .csv or the ov_table() name': '.csv か ov_table() の名前を変える',
    'octavo build makes them': 'octavo build で作られる',
    'could not read {file}: {why}': '{file} を読めない: {why}',
    'the table is empty': '表が空',
    '{file} is neither UTF-8 nor Shift_JIS — save it as UTF-8 CSV': '{file} は UTF-8 でも Shift_JIS でもない。CSV UTF-8 で保存し直す',
    '(read as Shift_JIS)': '（Shift_JIS として読んだ）',
    'made {file} -> .typ, .tex, .md': '{file} -> .typ, .tex, .md を作った',
    '{file} and the analysis both make the table {name} — rename one of them': '{file} と分析が同じ名前の表 {name} を作っている。どちらかの名前を変える',
    'a table could not be made, so this stops here (the PDF would show the old one). Fix the .csv above, then build again.': '表を作れなかったので、ここで止める（組むと古い表のままになる）。上の .csv を直してから、もう一度組む。',
    '{path} is already there (a table from the analysis?) — making {name}.csv would overwrite it. Pick another name': '{path} がもうある（分析が書いた表？）。{name}.csv を作ると上書きしてしまうので、別の名前にする',
    'fill it in (in VS Code, the Edit as a Table button; Excel works too)': '中身を書く（VS Code では「表として編集」ボタン。Excel でもよい）',
    'the caption line in the manuscript places it': '原稿のこの表題の行が、表を置く',
    'makes {files}': '{files} が作られる',
    'in a paper (from slides or lecture notes: ../{folder}/)': '論文の原稿に書く（スライド・講義ノートからは ../{folder}/）',
    'figures drawn in Typst': 'Typst で描いた図',
    '{n} not drawn since {n|its .typ|their .typ} changed': '{n} 個が、.typ を直したあと組まれていない',
    '{n|the one is|all # are} up to date': 'すべて最新',
    'octavo build draws them': 'octavo build で組まれる',
    '[pages]': '[ページ]',
    '[handout]': '[配布資料]',
    'typst is needed to cut the handout (octavo setup installs it)': '講義ノートを切り分けるには typst が要る（octavo setup で入る）',
    'a whole number, 0 or more': '0 以上の整数',
    'cut these printed page numbers instead (12-19,21)': '回の代わりに、このページ番号（印字の番号）で切る（12-19,21）',
    'typst failed:': 'typst が失敗した:',
    'the lecture notes (document name)': '講義ノート（文書名）',
    'cut the lecture handout into one PDF per session': '講義ノートを回ごとの PDF に切り分ける',
    '{file} has no page marks (was it written by octavo build --to typst from a lecture handout?)': '{file} にページの目印がない（講義ノートを octavo build --to typst で組んだものか）',
    "a size in points like '11pt'": "'11pt' のようなポイントの大きさ",
    'only these sessions (their ids, comma-separated; several make one PDF)': 'この回だけ（区切りの id をカンマ区切りで。複数なら1つの PDF にまとめる）',
    'handouts per session': '回ごとの配布資料',
    'print the result as machine-readable JSON': '結果を機械で読める JSON で出す',
    '{name} is not lecture notes (profile handout); only a lecture handout can be cut into sessions': '{name} は講義ノート（profile handout）ではない。回ごとに切り分けられるのは講義ノートだけ',
    '--pages takes page numbers like 12-19 or 3,5 (got {got})': '--pages には 12-19 や 3,5 のようにページ番号を書く（{got} だった）',
    '{key}: pages {pages} -> {file}': '{key}: {pages} ページ -> {file}',
    'no session {names} in {file} (sessions: {known})': '{file} に回 {names} がない（ある回: {known}）',
    '{file} has no session markers (::: {{.session #id}}), so there is nothing to cut. --pages 12-19 cuts by page number': '{file} に回の区切り（::: {{.session #id}}）がないので、切り分けられない。--pages 12-19 ならページ番号で切れる',
    'nothing to restate for {names} (no block with that label)': '{names} は再掲できない（そのラベルのブロックがない）',
    'put the cover and the contents in front': '表紙と目次を前に付ける',
    'a different width from the rest of this file': 'この原稿のほかの箇所と字下げの幅が違う',
    'Date format': '日付の書式',
    'Font size': '文字の大きさ',
    '{n} nested list {n|item is|items are} out of line (line a nested item up with its parent\'s text: 2 spaces under "- ", 3 under "1. ")': '入れ子の箇条書きで字下げが揃っていないものが {n} 個ある（子の項目は親の本文の桁に揃える: 「- 」の下なら 2 字、「1. 」の下なら 3 字）',
    'Lecture handout': '講義ノート（A4 プリント）',
    'Body font': '本文の書体',
    'Number of the first section': '最初の節の番号',
    'New page at': '改ページする位置',
    'too shallow to nest (it becomes a separate list)': '字下げが足りず入れ子にならない（別の箇条書きになる）',
    'Japanese and English works in their own forms': '日本語と英語の文献を別の形で組む',
    'Form of Japanese works': '日本語の文献の形',
}
