// =====================================================================
//  English-primary paper template (Typst)
//
//  For papers written mainly in English with occasional Japanese (proper
//  nouns, organization names). For Japanese-primary papers use paper/ja/main.typ.
//
//  **Hand-managed.** `octavo new paper <name>` puts it in papers/<name>/, next
//  to the manuscript, and every build copies it into build/typst/<name>/ — so
//  edit the copy under papers/. body.typ / abstract.typ are generated by
//  `octavo build`; do not edit them (overwritten on the next run).
//
//    octavo build <name> --to typst
//    cd build/typst/<name> && typst compile --root ../../.. main.typ
//    (without --root, ../../../figures cannot be read. octavo build --compile
//     passes it for you)
//
//  How citations are handled is set by typst_citations in octavo.config.py:
//
//    'csl' (default)  pandoc --citeproc writes CSL-formatted strings into
//                     body.typ, with the bibliography at its end.
//                     -> the #bibliography(...) below is **not used**
//    'native'         body.typ carries Typst #cite() calls and the
//                     #bibliography(...) below typesets the list
//
//  **Unlike LaTeX, no fonts are bundled.** The font list below assumes the
//  machine actually has them.
//    - `typst fonts` lists what is installed
//    - Libertinus Serif ships with Typst; the CJK fallback does not
//      (on Linux: sudo apt install fonts-morisawa-bizud-mincho fonts-noto-cjk;
//       on macOS: brew install --cask font-biz-udmincho; bash setup.sh installs
//       them, Noto takes over if BIZ UD is missing, and Hiragino — which every
//       Mac has — if Noto is missing too)
//    - to use fonts kept with the project:
//      typst compile --root ../../.. --font-path ../../../fonts main.typ
// =====================================================================

#set document(title: "Title of the Paper", author: "Author Name")
#set page(paper: "a4", margin: 1in, numbering: "1")
// Latin first, with a CJK face behind it for the occasional Japanese word
#set text(font: ("Libertinus Serif", "BIZ UDMincho", "Noto Serif CJK JP",
                 "Hiragino Mincho ProN"),
          lang: "en", size: 11pt)
#set par(justify: true, leading: 0.8em)
#set heading(numbering: "1.1")
#show figure.caption: set text(size: 9pt)

// Blind review. flags.typ is rewritten on every build
// (#let anonymous = true / false), so a normal build always clears it.
#import "flags.typ": anonymous

#align(center)[
  #text(size: 16pt, weight: "bold")[Title of the Paper]
  #v(0.8em)
  #if anonymous [
    #text(size: 10pt)[[Author details removed for blind review]]
  ] else [
    Author Name \
    #text(size: 10pt)[Affiliation] \
    #text(size: 10pt)[#link("mailto:email@example.ac.jp")]
  ]
]
#v(1.5em)

#heading(numbering: none)[Abstract]
#include "abstract.typ"

#pagebreak()
#include "body.typ"

// ---- only with typst_citations: 'native' ------------------------------
// #pagebreak()
// #bibliography("../../../literature.bib", style: "chicago-author-date",
//               title: "References")

// If there is an appendix (run octavo build <name> --to typst --appendix first)
// #pagebreak()
// #include "appendix.typ"
